Implement preview storylines feature
ramp4-pcar4/storylines-editor pull request #104
Opened 2023-02-21 21:11 UTC by yileifeng

Closes #7 

Haven't had the time to thoroughly test every edge case but seems to work on most cases. The feature is meant to be for previewing unsaved changes before committing to any saves to server. One issue that still needs to be addressed is how to store the `configFileStructure` object so that it can be preserved and the preview mode can be opened in a new tab (can be opened as separate issue after).

2023-02-22 19:45 UTC, spencerwahl commented
I assume you can get back from the preview to editing without losing everything?

2023-02-28 18:06 UTC, yileifeng commented
That would work as long as we redirect back to the editor route after #89 is completed, but am currently trying to get the new tab option working.

2023-03-02 14:01 UTC, yileifeng commented
[Demo](https://ramp4-pcar4.github.io/storylines-editor/preview-storylines/#/en/editor)

Added a new option to preview a saved product in new tab as a new route `'/:lang/editor-preview/:uid'`, while previewing current product with unsaved changes will stay on the same tab to have access to the `configFileStructure` object.

2023-03-07 20:00 UTC, RyanCoulsonCA approved these changes
> Reviewed 6 of 13 files at r1, 7 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-07 20:33 UTC, mohsin-r requested changes
Not sure if I'm doing something wrong, but previewing in a new tab doesn't seem to display the logo image, maps, slideshows etc.

> Reviewed 6 of 13 files at r1, 7 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104#-:-NPxlb-N6AOBHR6w0k-3:b6pe3e9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-07 20:49 UTC, yileifeng reviewed
Previewing saved products are fetched from the main `/public` folder where the `0000...` test folder is stored. When we save changes right now we are uploading to the TARGET path `server/public` folder instead.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104#-:-NPxoJQxCzn0WsVMT9VD:bjopi42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-07 21:57 UTC, mohsin-r reviewed
Interesting...I tried copying the product to `/public` but maps and images still don't work. All the text is ok though.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104#-:-NPy3A0c2ySN-kxxYvcU:b-vu0lj2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-08 13:55 UTC, yileifeng reviewed
Guessing this is because we don't have any folders pushed to the repo other than `0000` so accessing new asset files will fail. Whereas we are using an express route to retrieve the config file initially from the server which means the text loads fine. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104#-:-NQ0TsXy2p-VgsHDbhYl:b-vad4zm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-08 14:45 UTC, mohsin-r approved these changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-09 15:06 UTC, merged