Provide option to make single panel the full slide
ramp4-pcar4/storylines-editor pull request #110
Opened 2023-02-23 20:42 UTC by mohsin-r

Closes #100.

You can now make the right panel the full slide via a checkmark. This introduced some edge cases with dynamic panels, which I have handled as follows:
* When you have two panels and the right panel is made dynamic, you will automatically make the right panel take up the full slide as before, and the checkmark will be checked.
* When you have one panel that is dynamic, the checkbox is disabled so you cannot go to two panels.
* When you have one panel that is dynamic and you change it to another type, you no longer go back to two panels automatically, and you need to toggle the checkbox manually. This was done to avoid the case where the user chooses to have one panel, but changing from dynamic to something else undoes their choice. To be able to get both behaviours (i.e. dynamic panel makes two panels but only if the user didn't hit the box), we'd essentially need to store "user wants one panel" somewhere in the config/file system to remember that info. An extra click didn't feel worth the effort to me, so I went with this behaviour.

Feel free to let me know if any changes are needed to the behaviour above.

2023-02-24 20:54 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-02-27 18:29 UTC, roryhofland requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: all files reviewed, 1 unresolved discussion (waiting on @mohsin-r)

___
*[`src/components/editor/slide-editor.vue` line 94 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110#-NPJ71Gb2oBPqqInFk-G:-NPJ71Gb2oBPqqInFk-H:b-x38ruz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/77755f9d70b2616809006efb9afd5dff6b10e592/src/components/editor/slide-editor.vue#L94)):*
> ```Vue
>                     class="border-t border-l border-r"
>                     :class="panelIndex == 1 ? 'border-black' : 'border-white'"
>                     v-if="currentSlide.panel.length === 2"
> ```

Since only the right panel can be a single panel I think it would make sense to hide the 'Left Panel' button, it's a little confusing right now since selecting the checkbox appears to do the opposite of what it says, even though the functionality is the same.

Alternatively, the remaining panel button could be renamed 'Fullscreen Panel' or something.


<!-- Sent from Reviewable.io -->

2023-02-28 13:55 UTC, mohsin-r reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @roryhofland and @RyanCoulsonCA)

___
*[`src/components/editor/slide-editor.vue` line 94 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110#-NPJ71Gb2oBPqqInFk-G:-NPNIOTUEp1W8nTUiHN-:blmr31v) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/77755f9d70b2616809006efb9afd5dff6b10e592/src/components/editor/slide-editor.vue#L94)):*
<details><summary><i>Previously, roryhofland (Rory Hofland) wrote…</i></summary><blockquote>

Since only the right panel can be a single panel I think it would make sense to hide the 'Left Panel' button, it's a little confusing right now since selecting the checkbox appears to do the opposite of what it says, even though the functionality is the same.

Alternatively, the remaining panel button could be renamed 'Fullscreen Panel' or something.
</blockquote></details>

Good point. Donethanks for renaming it to "Fullscreen Panel" as that felt clearer to me.


<!-- Sent from Reviewable.io -->

2023-02-28 15:10 UTC, roryhofland approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-02-28 21:03 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-03-01 16:47 UTC, spencerwahl approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-03-01 18:28 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-03-01 18:29 UTC, merged