New Metadata Fields
ramp4-pcar4/storylines-editor pull request #113
Opened 2023-02-27 16:19 UTC by roryhofland

Closes #91, #98.

### Changes
- Intro slide title and subtitle can be configured via the metadata panel
- Intro slide logo can now be removed from metadata
- Logo source will no longer load as `undefined`

2023-02-28 14:06 UTC, mohsin-r requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113)* status: all files reviewed, 2 unresolved discussions (waiting on @roryhofland)

___
*[`src/components/editor/editor.vue` line 297 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113#-NPNKVSA8nO8l7yn2XJW:-NPNKVSA8nO8l7yn2XJX:br2gtil) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/396b54ea38ab8069d77ea1cf5c6694e43e96cb9b/src/components/editor/editor.vue#L297)):*
> ```Vue
>                     src: ''
>                 },
>                 title: 'Test Config Intro Slide',
> ```

Can we remove this default? It seems inconsistent for this to be the only field that has one. 
___
*[`src/components/editor/metadata-editor.vue` line 17 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113#-NPNL29tBbxg4nKhlwj9:-NPNL29tBbxg4nKhlwjA:b9e7udu) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/396b54ea38ab8069d77ea1cf5c6694e43e96cb9b/src/components/editor/metadata-editor.vue#L17)):*
> ```Vue
>             name="introTitle"
>             :value="metadata.introTitle"
>             @change="$emit('metadata-changed', $event.target.name, $event.target.value)"
> ```

This is not your fault, but for better code quality, we can write a method below that does this and have all the fields just call that.


<!-- Sent from Reviewable.io -->

2023-02-28 15:59 UTC, roryhofland reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @mohsin-r)

___
*[`src/components/editor/editor.vue` line 297 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113#-NPNKVSA8nO8l7yn2XJW:-NPNjy2-EEKLqqBGoprn:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/396b54ea38ab8069d77ea1cf5c6694e43e96cb9b/src/components/editor/editor.vue#L297)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

Can we remove this default? It seems inconsistent for this to be the only field that has one. 
</blockquote></details>

Donethanks
___
*[`src/components/editor/metadata-editor.vue` line 17 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113#-NPNL29tBbxg4nKhlwj9:-NPNk-2D790HUAjSWFhX:bfjrmue) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/396b54ea38ab8069d77ea1cf5c6694e43e96cb9b/src/components/editor/metadata-editor.vue#L17)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

This is not your fault, but for better code quality, we can write a method below that does this and have all the fields just call that.
</blockquote></details>

Agree, donethanks


<!-- Sent from Reviewable.io -->

2023-02-28 21:03 UTC, spencerwahl approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)



<!-- Sent from Reviewable.io -->

2023-03-01 14:29 UTC, yileifeng approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @roryhofland)



<!-- Sent from Reviewable.io -->

2023-03-01 18:29 UTC, merged