load both lang configs, allow copying between langs
ramp4-pcar4/storylines-editor pull request #140
Opened 2023-03-15 13:26 UTC by spencerwahl

Closes #69 #70 

Both configs are loaded at the start and stored in `this.configs` `.en` and `.fr`.
`configFileStructure.config` renamed to `configFileStructure.zip` and the configs are now passed around under `configFileStructure.configs`.

Added a button that opens a modal for copying slides from the other language, either all at once or one at a time.

Switching langs currently runs into the router "bug" where it shows the metadata edit page rather than staying on the main editor, clicking next brings you to the proper view.

2023-03-20 17:33 UTC, roryhofland requested changes
Not sure if this is a part of the router bug, but switching lang configs and hitting next into the editor doesn't update the current slide. So going from `en` config into a `fr` config and going back into the editor displays an `en` slide, which resolves when switching to another slide.

> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140#-:-NR-3UOzACPGPmrXMt1_:belb32x)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)

___
*[`src/components/editor/slide-toc.vue` line 36 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140#-NR-30tC9Zvv95GVgFF8:-NR-30tD92MzhnCoO8x9:btmcvh5) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f038a7961cde4ccd5ffec4ed0c2a5e2d2d876bd5/src/components/editor/slide-toc.vue#L36)):*
> ```Vue
>                         <select v-model="selectedForCopying">
>                             <option
>                                 v-for="(slide, index) in configFileStructure.configs[lang === 'en' ? 'fr' : 'en']
> ```

The slide copy selector overflows when slide titles are too long
![2023-03-20 13\_27\_05-RAMP Storylines — Mozilla Firefox.png](https://files.reviewableusercontent.io/images/reviewable/89807997/MSoGOcAhLALJvVudvfnC9OQL/2023-03-20%2013_27_05-RAMP%20Storylines%20%E2%80%94%20Mozilla%20Firefox.png)


<!-- Sent from Reviewable.io -->

2023-03-22 19:23 UTC, mohsin-r requested changes
There's also a couple of issues with editing the metadata on the config loading page (the one before the main slide editor):
* When editing a field, there is no way to save it if you want to switch languages to edit the other language's metadata and the changes always get lost. Clicking the save changes in the bottom left corner doesn't seem to work. 
* When creating a new product, it looks like editing the metadata for one language also edits it for the other language.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140#-:-NR9jTEhAnlEpbuGbMrL:b-71dvz8)* status: all files reviewed, 1 unresolved discussion (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2023-03-22 19:38 UTC, spencerwahl reviewed
> switching lang configs and hitting next into the editor doesn't update the current slide.

fixed

> When creating a new product, it looks like editing the metadata for one language also edits it for the other language.

Yes the metadata is copied over to the other language on purpose at the start. At worst it should be equivalent to not copying it and otherwise saves users doing the same thing twice (even if its just the logo).

> When editing a field, there is no way to save it if you want to switch languages to edit the other language's metadata and the changes always get lost. Clicking the save changes in the bottom left corner doesn't seem to work.

This is a good point, the original use case was just "choose a language, edit metadata, edit that language and switch over". I think this is a good thing to log as a new issue.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140#-:-NR9nxoV9J8gTsTIV81a:bn3gevq)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @mohsin-r, @roryhofland, and @RyanCoulsonCA)

___
*[`src/components/editor/slide-toc.vue` line 36 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140#-NR-30tC9Zvv95GVgFF8:-NR9p2gC4t5xtq9jumS8:bb6un1j) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f038a7961cde4ccd5ffec4ed0c2a5e2d2d876bd5/src/components/editor/slide-toc.vue#L36)):*
<details><summary><i>Previously, roryhofland (Rory Hofland) wrote…</i></summary><blockquote>

The slide copy selector overflows when slide titles are too long
![2023-03-20 13\_27\_05-RAMP Storylines — Mozilla Firefox.png](https://files.reviewableusercontent.io/images/reviewable/89807997/MSoGOcAhLALJvVudvfnC9OQL/2023-03-20%2013_27_05-RAMP%20Storylines%20%E2%80%94%20Mozilla%20Firefox.png)

</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-22 19:56 UTC, mohsin-r approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140)* status: all files reviewed, 1 unresolved discussion (waiting on @roryhofland)



<!-- Sent from Reviewable.io -->

2023-03-30 18:27 UTC, yileifeng approved these changes
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @spencerwahl)



<!-- Sent from Reviewable.io -->

2023-03-31 17:40 UTC, merged