Fix Vue routing to separate slide editor from metadata editor
ramp4-pcar4/storylines-editor pull request #153
Opened 2023-03-27 19:09 UTC by yileifeng

Closes #89, #129 

**Changes**: 
- added new routes: `/:lang/editor-main/:uid` for the slide editor (requires UID as parameter), `/:lang/editor-metadata/:uid` for metadata page with UID as parameter, `/:lang/editor/:uid` that redirects to the metadata page
- fixed back button in preview mode redirecting back to the slide editor (#129) but still should open in new tab  (opened #152)
- refactored code to separate metadata component and its logic from the main slide editor
- add functionality to load existing Storylines product for different page views if UID param is passed in route 
- renamed some files

**Testing**: 
Test transitioning between page views, save functionality, and loading products by passing in UID as URL parameter. Additionally, check if all recently merged PR changes functionality in case any changes were lost during rebase.

2023-03-28 16:06 UTC, mohsin-r requested changes
Pretty neat changes! Three points that came to mind:

* This might be a bit nitpicky, but I'm not too sure that `metadata-editor.vue` is the right name for that file anymore since its doing a whole lot more than simply "editing the metadata".
* The unsaved changes indicator seems to be appearing as soon as you go into the main editor. For example, I'll save the product, preview, then go back to product, and it'll trigger the indicator before changes are made.
* Clicking on "View Saved Product" takes you to `/editor-main/editor-preview/Test`.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NRcu6OtC3RXlCbCbmgw:b-d6xkwu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-28 17:28 UTC, mohsin-r reviewed
Found another bug while testing. When you create a new product, preview it (without saving) and then click back, you get the UUID does not exist.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NRdFN457EuNyEXsOxdO:b40tfbt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-03-29 15:21 UTC, yileifeng reviewed
Open to any renaming suggestions for `metadata-editor` but left for now. Unsaved changes should be fixed as it was detecting the slides being initialized, added a timeout as couldn't find a better solution. The saved product and all transitions between routes have been reworked and should be fixed now (waiting on build update). 

For the preview mode, it actually does not work as is right now because the changes are not being saved before jumping to the preview mode, which means we are just loading in the saved product when we go back to the editor view. We could choose to save changes but this wouldn't make much sense as this function is for previewing unsaved changes. This is why I think the best solution is just to implement the new tab for preview mode #152, and this will also fix the bug you mentioned above. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NRhvuaS0Pnusi8WkYDD:b-kbkx2s)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-03-30 20:44 UTC, mohsin-r approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-03 14:39 UTC, RyanCoulsonCA approved these changes
> Reviewed 5 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-04 17:55 UTC, yileifeng reviewed
Rebased changes from lang switching. There seems to be an issue reloading content after switching languages in the main slide editor so will open a new issue for that. Would be helpful if everyone could take a quick look and test to see if everything still functions as intended after the rebase. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NSCN8jsELOYDElZyawl:bawsmkw)* status: 4 of 12 files reviewed, all discussions resolved (waiting on @mohsin-r and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-04 18:35 UTC, mohsin-r approved these changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-04 18:55 UTC, spencerwahl requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)

___
*[`src/components/editor/metadata-editor.vue` line 534 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-NSCbRUVB0zgwlvdAH6Q:-NSCbRUVB0zgwlvdAH6R:b-dzxbbl) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2a47efd3f343207243061ac9604967602d46f62d/src/components/editor/metadata-editor.vue#L534)):*
> ```Vue
>         this.lang = to.params.lang;
>         this.uuid = to.params.uid;
>         this.$i18n.locale = this.lang;
> ```

I think this function is the reason the language switching isn't working, `this.lang` is being used to denote which config is being edited but it is being used here as which lang the page is in.


<!-- Sent from Reviewable.io -->

2023-04-04 19:25 UTC, roryhofland approved these changes
Would we want the back button in the main editor to go back to the `/editor-metadata/uuid`endpoint instead of the landing page? Not a big deal either way, and if it causes extra issues with saving and whatnot then it's probably not worth the trouble.

Also very minor but when loading a config directly through a URL the 'loaded config', or 'uuid does not exist' message triggers twice. Guessing it's firing twice based on the way it loads the config then the editor, but I can take a look at this in #154 after this is merged.

> Reviewed 5 of 8 files at r1, 4 of 4 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NRifSk00bkL2yxgtwCi:b-5iznem)* status: all files reviewed, 1 unresolved discussion (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-05 13:20 UTC, yileifeng reviewed
For the back button, it shouldn't cause any more issues and I agree it makes sense to link it back to the `metadata/uid` route. The original issue https://github.com/ramp4-pcar4/storylines-editor/issues/94 seems to state a link back to the landing page though so unsure if we should make the change.

The second trigger was caused by the `beforeRouteUpdate` calling a second fetch to config when detecting route changes (don't believe this is required anymore). Removed and should fix this bug. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-:-NSGYH6e0e1CAQ7mWKKs:bihxfp3)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @mohsin-r, @roryhofland, and @spencerwahl)

___
*[`src/components/editor/metadata-editor.vue` line 534 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/153#-NSCbRUVB0zgwlvdAH6Q:-NSGZbPV7K4OrBfSLPyY:bc7o127) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2a47efd3f343207243061ac9604967602d46f62d/src/components/editor/metadata-editor.vue#L534)):*
<details><summary><i>Previously, spencerwahl (Spencer Wahl) wrote…</i></summary><blockquote>

I think this function is the reason the language switching isn't working, `this.lang` is being used to denote which config is being edited but it is being used here as which lang the page is in.
</blockquote></details>

This should be fixed now, along with passing the config language as a separate prop to not disrupt the route param language.


<!-- Sent from Reviewable.io -->

2023-04-13 11:19 UTC, merged