Add reload button
ramp4-pcar4/storylines-editor pull request #157
Opened 2023-03-30 20:48 UTC by RyanCoulsonCA

Closes #149 

This PR adds a reload button to the editor. When clicked, it will undo any changes that have been made since the last save by re-fetching the product from the server and re-loading it.

I currently have this reload button set to appear whenever the 'Unsaved Changes' indicator is showing. This can be changed based on any feedback you may have!

2023-04-04 17:39 UTC, mohsin-r requested changes
Looks good! Two things that come to mind:

* I'm not a design expert, but I feel like it would be better to have the reset text next to the icon to match the other buttons in that row. Feel free to weigh in on design choices.
* When you create a new product, save it, and then edit some stuff, the reset button does not appear. Should it appear in this case?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/157#-:-NSCL2905TgjusrRAU0h:b-cmz9x1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-11 18:31 UTC, RyanCoulsonCA reviewed
Sorry, somehow missed this review. I've made the following changes:
- added the 'reset changes' text to the button
- you should now be able to reset the project for new products too. Clicking the reset button before saving will wipe the whole config.
- when a new project is saved, `editExisting` is now set to true so that clicking the reset button will pull the files from the server

Working on re-basing this PR now but I'm running into a few issues.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/157#-:-NSl_4JsCUoZTxVRwyi3:b-vet5um)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-13 19:50 UTC, roryhofland requested changes
When resetting changes on a new unsaved product I get bumped back to the metadata editor only about 20% of the time. It usually remains on the slide editor.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/157#-:-NSw8wA96wPpwz62Jin8:bt9whz9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-18 14:20 UTC, RyanCoulsonCA commented
Merged these changes into #175

2023-04-18 14:20 UTC, closed without merging