Implement previewing unsaved changes in new tab
ramp4-pcar4/storylines-editor pull request #167
Opened 2023-04-03 20:43 UTC by mohsin-r

Closes #152.

A question that comes to mind is now that previewing in new tab works, do we want to remove the option of "viewing saved product", as the user could just open a preview at the start of the session and then open another one for their new changes to see the difference. I have kept it in for now.

2023-04-04 18:03 UTC, yileifeng approved these changes
Don't have a strong opinion on this, but I think it should be fine to remove the viewing saved product since there is not a strong use case for it and removing can lessen any confusion between the two options. Also, although less intuitive the user can view a saved product through the route `en/editor-preview/UID`.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NSCPO6iBfigJ-lzzm86:b-ynxlkq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-04 18:07 UTC, yileifeng reviewed
Having this route actually makes me lean more heavily towards just removing the option now lol

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NSCRMT7EEGedKuEdsRX:b-9izxbq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-05 18:57 UTC, RyanCoulsonCA requested changes
Most things seem to work great for me, but I did notice one thing: I create a new image slide and upload an image, it doesn't seem to be displaying when I go to preview it.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NSHlaP15fH18THJ66Au:brljtug)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-05 20:10 UTC, mohsin-r reviewed
I believe this bug is unrelated to the preview feature as this strangely only seems to happen when you have one image in the slideshow - multiple images works fine. I'll open a new issue for this.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NSI13CIB2tOj3yeL3eX:b-ljeh81)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-05 22:35 UTC, mohsin-r reviewed
> I'll open a new issue for this.

Nevermind, I pushed a fix in this PR instead. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NSIYnlN8ARWkCfxvn12:b987hnh)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-17 15:42 UTC, mohsin-r reviewed
Rebased. Additionally, removed the option to view the saved product.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167#-:-NTEsPRO6woLHQJ8jl-m:b-fx96rg)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-18 14:14 UTC, roryhofland approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2023-04-19 13:29 UTC, merged