add functionality to metadata save button; fix logo upload
ramp4-pcar4/storylines-editor pull request #175
Opened 2023-04-17 19:00 UTC by RyanCoulsonCA

Closes #155 

Changes in this PR:
- [ ] The `Save Changes` button when editing product metadata will now upload the product changes to the server.
- [ ] Removed the `Save Changes` button when creating a new product, as the config is not yet created.
- [ ] Fixed a pre-existing issue (not logged) where opening the metadata popup in the main editor and then saving the product seemed to overwrite the logo.

2023-04-19 17:46 UTC, yileifeng requested changes
If the reset changes will be taking the user back to the metadata page, it will be needing a user confirmation box before navigating away. 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/175#-:-NTPbjA3DZwgYRIm-tM9:b4frwsu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-19 19:38 UTC, RyanCoulsonCA reviewed
Good point, donethanks

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/175#-:-NTQ0WFB1uXdPzJpJ9L0:b-o4epv3)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @spencerwahl and @yileifeng)



<!-- Sent from Reviewable.io -->

2023-04-19 20:44 UTC, mohsin-r approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-20 13:16 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-21 14:21 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-04-24 13:26 UTC, merged