fix long names adding a horizontal scrollbar to app
ramp4-pcar4/storylines-editor pull request #221
Opened 2023-05-18 15:26 UTC by RyanCoulsonCA

Closes https://github.com/ramp4-pcar4/story-ramp/issues/340 (same fix as main repo)

This PR fixes an issue where long names just extend the width of the screen. Ellipses are now added to the end of the title. I did attempt to see how it would work to have the title wrap to the next line, but it causes a ton of issues with how we have the second slide stick to the top on mobile view.

As far as the chart problem goes, I'm unable to test the exact product that the issue was found on, but other charts seem to work well.

2023-05-24 15:08 UTC, mohsin-r approved these changes
Not sure if I'm doing something wrong but it seems to be wrapping onto the second line for me rather than showing the ellipsis. Not complaining though since it is visible lol.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWDHOHJ8u3OKAnmJzBb:bwsfxif)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-24 17:36 UTC, spencerwahl approved these changes
Are you looking at the title in the top bar or the big one, this is for the small title in the top bar.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWDpFva61OvipJNnChA:b-g5d152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-24 18:28 UTC, mohsin-r approved these changes
The one in the top bar.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWE0BPr-hg1CphU6ZKm:b-7base)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-24 19:22 UTC, RyanCoulsonCA reviewed
Interesting, is anyone else able to reproduce this? I've tested on two different computers and on mobile and can't seem to get this to happen :thinking: 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWEC_Ub5QJXkqzQCFQG:b-egtaax)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-24 20:05 UTC, spencerwahl approved these changes
WOMM on chrome and FF

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWEMJqc9sh4ibEytgpd:b4arej5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-25 13:11 UTC, yileifeng requested changes
I think the reason is the styles are not applied to the preview component since I got the same behavior Mohsin mentioned in preview mode. The styling you applied in `story.vue` will also need to be added to `preview.vue`.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWI0TcvDKaAAhvlN-Ds:b-4gi1hr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-25 17:50 UTC, RyanCoulsonCA reviewed
I've added the styling to the preview file as well, should work now

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221#-:-NWJ147EBSZIy6-Hair8:b2sd97v)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @mohsin-r, @spencerwahl, and @yileifeng)



<!-- Sent from Reviewable.io -->

2023-05-25 18:06 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-25 18:20 UTC, mohsin-r approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-05-26 14:05 UTC, merged