test
ramp4-pcar4/storylines-editor pull request #233
Opened 2023-06-07 19:03 UTC by roryhofland

2023-06-08 14:41 UTC, spencerwahl requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/233)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @roryhofland)

___
*[`src/components/editor/text-editor.vue` line 123 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/233#-NXQRyUj86kiIMJmIKgB:-NXQRyUkDyv9r25AvDBb:b-h1gmx9) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/002020745ccd37f591f7c500174c345086367a17/src/components/editor/text-editor.vue#L123)):*
> ```Vue
>         this.configFileStructure.assets[this.lang].file(file.name, file);
> 
>         // Here is just an example
> ```

Was this a comment copied from an example? because the below thing looks like the proper code


<!-- Sent from Reviewable.io -->

2023-06-08 17:09 UTC, RyanCoulsonCA reviewed
> Note: inline images do not appear in the markdown preview or storylines preview due to the way files are referenced in these pages.

Since the preview feature is intended to work without needing to save the product, it accesses images directly from the ZIP file ([see here](https://github.com/ramp4-pcar4/storylines-editor/blob/main/src/components/panels/slideshow-panel.vue#L92)). 

The library we're using to render markdown in the text panels (Markdown-it) just knows to display an image based on the source provided in the markdown, so it's trying to display an image with the path provided ( for example, `/00000000-0000-0000-0000-000000000000/assets/en/example.jpg`), but that path doesn't actually exist on the server yet and there isn't any logic to fetch the file from the ZIP so it just displays a broken image. 

[Markdown-it supports custom rendering](https://markdown-it.github.io/markdown-it/#Renderer.prototype.rules), so we can add some custom logic to the image rendering function to check whether the image exists in the ZIP file.

The problem with the markdown editor is probably the same as the Markdown-it problem, but the fix might be trickier because it doesn't seem like there is any way to add custom rendering. I don't have any good ideas for this one at the moment, if anyone else has any ideas please post!

I'm not sure how much work this involves, maybe it's worth a discussion for whether we want to do this now or push it to the next phase.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/233#-:-NXQaCC2Evb4XDlB-wAN:b5hg2ys)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @roryhofland and @spencerwahl)



<!-- Sent from Reviewable.io -->

2024-02-29 18:46 UTC, dan-bowerman commented
The issue here may be that the images need to be committed to the zip and not dumped to the public folder. Needs investigation.

2024-08-22 14:18 UTC, yileifeng commented
Much outdated and can reference code in open issue again if becomes requirement

2024-08-22 14:18 UTC, closed without merging