Highcharts number formatting based on language
ramp4-pcar4/storylines-editor pull request #250
Opened 2024-02-28 21:48 UTC by KashishMistry

For #226 

**Changes**
- Added the `thousandsSep` option to set the thousands separator to `,` for the editor in English and ` ` for the editor in French

**Notes**
English Example:
![highcharts en](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/7008534a-d0cd-4150-acd8-ff1c77516329)

French Example:
![highcharts fr](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/86660bf1-e776-497f-9817-f5468b73a5d9)

2024-02-29 13:52 UTC, yileifeng requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KashishMistry)

___
*[`src/components/editor/chart-editor.vue` line 154 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250#-Nrp7eDB8peXW8YyqCRm:-Nrp7eDCD1yk_EzqkINX:b-yo7uho) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/806d6df3c941c659df094f7e8f67be5790e16d4a/src/components/editor/chart-editor.vue#L154)):*
> ```Vue
>                 credits: {
>                     enabled: false
>                 },
> ```

No need to initialize the same options (title, subtitle, credits) twice for both langs


<!-- Sent from Reviewable.io -->

2024-02-29 15:24 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-02-29 21:32 UTC, dnlnashed approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-06 20:08 UTC, szczz approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-11 14:18 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/250)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-11 15:06 UTC, merged