Added option for horizontal table of contents
ramp4-pcar4/storylines-editor pull request #265
Opened 2024-03-14 15:20 UTC by KashishMistry

### Related Item(s)
https://github.com/ramp4-pcar4/story-ramp/issues/402 (not in this repo)

### Changes
- Added option for user to select between horizontal and vertical table of contents
- The default option is a vertical table of contents

### Notes
![toc orientation](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/ebf379c0-4621-4ebc-b50a-189ff3462494)

### Testing
Steps:
1. Open Project Metadata editor. Choose between horizontal or vertical table of contents.

There isn't a way to test whether the functionality works because there is another PR open in the story-ramp repo that is meant to implement the functionality. If there are any other methods to test, that would be appreciated, thanks!

2024-03-21 17:33 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @KashishMistry)

___
*[`src/components/editor/helpers/metadata-content.vue` line 75 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX0h_d5DNIIyTDbTl9:-NtX0h_d5DNIIyTDbTlA:bnnh1u0) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L75)):*
> ```Vue
>         <br />
>         <label class="mr-15">{{ $t('editor.tocOrientation') }}:</label>
>         <select class="border-solid border border-black p-1" name="toc" id="toc" @change="metadataChanged">
> ```

Tested this by running the server locally and checking the config manually after saving. Found a couple of things:

1. It doesn't seem like the orientation is being saved to the file. Changing the `name` attribute to `tocOrientation` should fix this.

2. The dropdown also doesn't default to the correct value. Try adding `v-model="metadata.tocOrientation"` here and add `tocOrientation` to the metadata prop (see other comment) and see if this works!
___
*[`src/components/editor/helpers/metadata-content.vue` line 95 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX3YV_DmZwWOgOCFuF:-NtX3YV_DmZwWOgOCFuG:bbdo1bo) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L95)):*
> ```Vue
> 
> export default class MetadataEditorV extends Vue {
>     @Prop() metadata!: {
> ```

Add `tocOrientation` here


<!-- Sent from Reviewable.io -->

2024-03-22 17:29 UTC, KashishMistry reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/helpers/metadata-content.vue` line 75 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX0h_d5DNIIyTDbTl9:-NtbCOig8Gid-50MX_z6:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L75)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Tested this by running the server locally and checking the config manually after saving. Found a couple of things:

1. It doesn't seem like the orientation is being saved to the file. Changing the `name` attribute to `tocOrientation` should fix this.

2. The dropdown also doesn't default to the correct value. Try adding `v-model="metadata.tocOrientation"` here and add `tocOrientation` to the metadata prop (see other comment) and see if this works!
</blockquote></details>

Donethanks.
___
*[`src/components/editor/helpers/metadata-content.vue` line 95 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX3YV_DmZwWOgOCFuF:-NtbCQ-M7tqEHm4XTMG6:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L95)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Add `tocOrientation` here
</blockquote></details>

Donethanks.


<!-- Sent from Reviewable.io -->

2024-03-22 19:34 UTC, RyanCoulsonCA approved these changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @KashishMistry)

___
*[`src/components/editor/helpers/metadata-content.vue` line 75 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX0h_d5DNIIyTDbTl9:-NtbdVp_5E61gg9ZIATh:b-xcga7m) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L75)):*
<details><summary><i>Previously, KashishMistry (Kashish Mistry) wrote…</i></summary><blockquote>

Donethanks.
</blockquote></details>

Looks good! If you load an existing product that doesn't have `tocOrientation` in the config the dropdown is blank, but I'm not sure that this is a huge deal as long as we display the vertical table of contents by default.


<!-- Sent from Reviewable.io -->

2024-03-25 19:21 UTC, yileifeng reviewed
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: all files reviewed, 1 unresolved discussion (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-03-25 19:37 UTC, KashishMistry reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/editor/helpers/metadata-content.vue` line 75 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265#-NtX0h_d5DNIIyTDbTl9:-Ntr6ReG6A3r0Dg8pvrU:b-aa242q) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/f36c2cc8b6ae847e46059c35091c2a9d38db432e/src/components/editor/helpers/metadata-content.vue#L75)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Looks good! If you load an existing product that doesn't have `tocOrientation` in the config the dropdown is blank, but I'm not sure that this is a huge deal as long as we display the vertical table of contents by default.
</blockquote></details>

Yes, it should default to vertical if there is no `tocOrientation` specified


<!-- Sent from Reviewable.io -->

2024-04-02 18:10 UTC, szczz approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-04-03 20:37 UTC, RyanCoulsonCA approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-04 13:06 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/265)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-04 13:06 UTC, merged