Option for centering content
ramp4-pcar4/storylines-editor pull request #285
Opened 2024-04-17 19:47 UTC by KashishMistry

### Related Item(s)
[#403](https://github.com/ramp4-pcar4/story-ramp/issues/403) in `story-ramp` repo

### Changes
- This issue is logged in the `story-ramp` repo, however the changes needed to be implemented in `storylines-editor` to allow users to manipulate the `customStyles` property for each panel
- `centerPanel` allows the user to center content in each panel 
- `centerSlide` allows the user to center content in the overall slide (if the slide has two panels then the left panel is right-aligned and the right panel is left-aligned)

### Notes
Without centering:
![alignment normal](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/256c0a7c-9948-4f2e-9f84-6ebe29e14ed5)

When `centerPanel` is selected:
![alignment panel](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/7aa7dc65-0bc3-44c9-bfb3-cb56b9685f35)

When `centerSlide` is selected:
![alignment slide](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/fb2bdf88-9e82-422a-b298-a6e980b35126)

When there is only one panel and `centerSlide` or `centerPanel` is selected:
![alignment one](https://github.com/ramp4-pcar4/storylines-editor/assets/83516523/f5580a32-37ad-42fb-9de4-495a8d2f61c7)

### Testing
Steps:
1. Create a new slide
2. Select `Align panel content towards the middle` and preview to check the alignment of the content on the panel (should be centered relative to the panel).
3. Select `Align slide content towards the middle` and preview to check the alignment of the content on the slide (left slide should be right-aligned and right slide should be left-aligned).
4. Experiment with dynamic panels in particular to ensure the panels in `children` are being aligned correctly.

2024-04-24 13:28 UTC, yileifeng requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @KashishMistry)

___
*[`src/components/editor/slide-editor.vue` line 40 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285#-NwFHSuW2AUIuUa4DhrL:-NwFHSuW2AUIuUa4DhrM:bazym3w) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2b74c74e1bb659c3543f886a63ca76c43640cf74/src/components/editor/slide-editor.vue#L40)):*
> ```Vue
>                         />
>                         <span class="mx-2 font-bold">{{ $t('editor.slides.centerSlide') }}</span>
>                         <input
> ```

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/XoErtdzGJhk-myonUGGz5I7V/image.png)

The toggle checkboxes are not aligned with the text
___
*[`src/lang/lang.csv` line 115 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285#-NwFFrvvC5zdaGAJE7oG:-NwFFrvvC5zdaGAJE7oH:bdd3yat) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2b74c74e1bb659c3543f886a63ca76c43640cf74/src/lang/lang.csv#L115)):*
> ```CSV
> editor.slides.makeFull,Make the right panel the full slide,1,Mettre la diapositive complète dans le panneau de droite,1
> editor.slides.centerPanel,Align panel content towards the middle,1,Aligner le contenu du panneau vers le milieu,0
> editor.slides.centerSlide,Align slide content towards the middle,1,Aligner le contenu de la diapositive vers le milieu,0
> ```

Suggestion: how about rewording this to "Center panel content" and "Center slide content"? Would preserve some valuable space as well and could be more intuitive wording.


<!-- Sent from Reviewable.io -->

2024-04-24 13:47 UTC, KashishMistry reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @yileifeng)

___
*[`src/components/editor/slide-editor.vue` line 40 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285#-NwFHSuW2AUIuUa4DhrL:-NwFM4GE5NQnxerl8ZCg:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2b74c74e1bb659c3543f886a63ca76c43640cf74/src/components/editor/slide-editor.vue#L40)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/XoErtdzGJhk-myonUGGz5I7V/image.png)

The toggle checkboxes are not aligned with the text
</blockquote></details>

Donethanks.
___
*[`src/lang/lang.csv` line 115 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285#-NwFFrvvC5zdaGAJE7oG:-NwFM5Qi7mYVdxkCaYY7:b-ugpthe) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/2b74c74e1bb659c3543f886a63ca76c43640cf74/src/lang/lang.csv#L115)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Suggestion: how about rewording this to "Center panel content" and "Center slide content"? Would preserve some valuable space as well and could be more intuitive wording.
</blockquote></details>

Donethanks.


<!-- Sent from Reviewable.io -->

2024-04-24 14:12 UTC, yileifeng approved these changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-25 20:33 UTC, dnlnashed approved these changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-04-26 14:12 UTC, RyanCoulsonCA approved these changes
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/285)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @KashishMistry)



<!-- Sent from Reviewable.io -->

2024-05-02 17:05 UTC, merged