fix advanced editor validation; enhance the Storylines schema
ramp4-pcar4/storylines-editor pull request #319
Opened 2024-06-12 20:03 UTC by RyanCoulsonCA

### Related Item(s)
#318 

### Changes
- Fixes an issue where the JSON validator did not run unless you clicked the `Save` button at the bottom of the editor (was removed in a previous PR). It now validates the JSON as you write the config.
- If the user switches off the advanced editor with validation errors, they will be warned that the product may break but will be allowed to continue.
- The Storylines schema has also been enhanced. I tested this on every type of panel through the demo product (00000000-0000-0000-0000-000000000000), but try out some different products and let me know if you run into any validation errors when using the advanced editor.

### Notes
![validator-improved](https://github.com/ramp4-pcar4/storylines-editor/assets/25874602/9a757bc9-693d-414c-a1e7-a40df03d0fb3)

### Testing
Steps:
1. Open the sample page and load a product.
2. Click on a slide and open the advanced editor.
3. Make some config changes and check that the validator is working correctly. Test it out with both fake properties and real ones.
4. Check that existing slides with valid schema aren't showing as invalid.
5. Try switching off of the advanced editor with errors and ensure that the warning pops up.

2024-06-13 20:03 UTC, dnlnashed requested changes
Just wondering if we need to validate the JSON as well. When breaking the JSON syntax the warning doesn't appear, is this intended?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/319#-:-O-IAYItBuSxX7fBPmE6:b-61yoii)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-06-14 15:45 UTC, RyanCoulsonCA reviewed
The JSON editor has a handler to detect syntax errors so it's probably a good idea that we show those as well. Done!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/319#-:-O-MQ3TGAv5isXWhy9C4:b-iolxpx)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @dnlnashed)



<!-- Sent from Reviewable.io -->

2024-06-14 19:23 UTC, dnlnashed approved these changes
:thumbsup: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/319#-:-O-NC7Ls3bAGjanOr3Nw:b4c9lyr)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-06-17 14:45 UTC, yileifeng approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/319)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-06-19 14:52 UTC, merged