dynamic panel editor enhancements
ramp4-pcar4/storylines-editor pull request #358
Opened 2024-07-08 18:04 UTC by RyanCoulsonCA

### Related Item(s)
#342 

### Changes
- Disable the "Add New" button if the ID isn't filled out when adding a new panel.
- Fix issue with duplicate ID string being cut off.
- Added an additional confirmation step before deleting subpanels.

### Testing
Steps:
1. Open the demo page and load a product.
2. Create a dynamic panel and add some subpanels.
3. Try to add a new subpanel with no name and ensure that you can't click `Add new`.
4. Try to add a new subpanel with the same name as another subpanel. Ensure the error message pops up and it's not cut off.
5. Try to remove a subpanel and ensure the additional confirmation message pops before it is removed.

2024-07-15 20:05 UTC, yileifeng requested changes
Found two issues when testing: 
1. After creating a new dynamic panel, the first subpanel cannot be deleted (no action when removing).
2. When accessing an existing dynamic panel on the 0000 product (second slide), the config seems to be breaking the schema validator (resulting in other issues such as not being able to delete the slide). This also seems to happen when creating a new empty dynamic panel:  
![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/7Nngbmll6q_htNIojqdWyqy8/image.png)

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/31557789/bikBWZ4hK2AkjWLPe4q_ey2t/image.png)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/358#-:-O1rxzyE-bSDhEceJH5H:bsbph2a)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-16 15:35 UTC, RyanCoulsonCA reviewed
I've fixed the issue with deleting the first subpanel, and the issue with the new dynamic panel showing an error in the advanced editor. That version of the `0000` product seems to be quite outdated (notice that the slideshow entry still has the `images` property instead of `items`), which is why that's erroring.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/358#-:-O1wASye2tzR-0o_G0FQ:b47kmvw)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-18 12:49 UTC, yileifeng approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-07-24 21:13 UTC, dnlnashed approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-07-29 12:14 UTC, merged