Modify routes and add option to change config lang in preview mode
ramp4-pcar4/storylines-editor pull request #368
Opened 2024-07-23 17:53 UTC by yileifeng

### Related Item(s)
Closes #311 

### Changes
- [FEATURE] Adds change lang in preview mode
- [ROUTE] Removes preview route with no UID specified

### Testing
Steps:
1. Change languages in preview mode

2024-07-30 17:20 UTC, RyanCoulsonCA approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/368)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2024-08-02 19:44 UTC, dnlnashed requested changes
Noticed that when switching between the languages in preview mode multiple times the local server ends up crashing. Not sure how much of an issue this will be in prod.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/368#-:-O3J_OD7EJHCKf2U9glM:b-ijru28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2024-08-07 18:29 UTC, yileifeng reviewed
Did a rework for the preview component to save both lang configs and only trigger a refresh of the Vue component upon language toggle rather than relying on a server fetch. This should solve the issue as the server will not get overloaded. Should be a much faster page loadup time as well when switching languages.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/368#-:-O3i4tChBj4usaE0UG2P:b-ihk5cb)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @dnlnashed and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-08-08 19:12 UTC, dnlnashed approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/368)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2024-08-21 13:03 UTC, merged