Disable dragging feature of slide toc
ramp4-pcar4/storylines-editor pull request #372
Opened 2024-08-07 15:53 UTC by IshavSohal

### Related Item(s)
#323

### Changes
- Set the disabled prop to false in order to disable the dragging of items in the slide toc

### Testing
Steps:
1. Click to edit any storyline
2. Proceed to edit existing slides
3. Try to click and drag any slide up or down
4. Observe that the slide won't be picked up and dragged

2024-08-07 18:16 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-08-08 19:14 UTC, dnlnashed approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-08-09 12:50 UTC, szczz requested changes
Temporary blocker. I know the issue mentions that we should disable this functionality, but I think we should at least investigate a resolution to the issue. Additionally, if we do intend to remove it we should probably get rid of the draggable component.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372#-:-O3rAJUwA1pjtb_CJ8Jn:b-xb7x67)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-08-12 17:21 UTC, IshavSohal commented
I managed to get the dragging of the toc components to work by using the `list` prop instead of `v-model`. 

However, I noticed that we're using `title` as the item key for the draggable component, and that `title` is not guaranteed to be unique between the slides. This causes 'duplicate key' errors to occur when dragging slides in the toc that have the same title as another slide.

What would be a good solution for this? Perhaps we could state in the schema that the title of a slide has to be unique, as well as ensuring that the title of new slides are unique before adding them in. 





<!-- Sent from Reviewable.io -->

2024-08-12 17:38 UTC, yileifeng reviewed
Was about to suggest we combine the title + slide index as the key for a simple workaround, but I see that's already being done in the existing code: `:key="element.title + index"`. Does this not work?

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372#-:-O46eR7D86Bi3NwNqPdT:b30rq8u)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @dnlnashed and @szczz)



<!-- Sent from Reviewable.io -->

2024-08-12 18:41 UTC, IshavSohal commented
It seems like the issues go away when I set `title` to an empty string (in fact any random string). I'm not too sure why that is, as well as if that's problematic. 





<!-- Sent from Reviewable.io -->

2024-08-16 19:39 UTC, szczz reviewed
Do you mean setting the item-key to empty or a random string? I think Yi-Lei's suggestion of title + index would be preferred as we don't want to leave item-key empty. I've tested the dragging functionality and it works well though.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372#-:-O4RfZvXDmsRPLIyJhcN:b2rnr3w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-08-19 19:52 UTC, IshavSohal commented
Yep meant to say `item-key`, mb. Since I couldn't access the index directly within the draggable component tag, I set `item-key` to a function that returns the title + index. The 'duplicate key' error should be gone now. 





<!-- Sent from Reviewable.io -->

2024-08-28 18:31 UTC, szczz approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/372)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-08-29 12:21 UTC, merged