Create shared assets folder
ramp4-pcar4/storylines-editor pull request #414
Opened 2024-10-23 20:38 UTC by IshavSohal

### Related Item(s)
#385 

### Changes
- Added a shared assets folder. 
    - When an asset is uploaded within the config of one lang that already exists in the other langs config, it gets removed from the other lang's assets folder, and added to the shared assets folder
    - When an asset is removed from a lang's assets folder, the asset in the current lang's assets folder has its source count set to 0, and it is added onto to the source count of the asset in the shared assets folder. This is because all instances of that asset within the current lang's config will be set to refer to the shared assets folder (once `save changes` is clicked, that is)
- Modified `deleteVideo()` to decrement the source count of video asset (if its local), and to remove it from `configFileStructure`
- Added `assetOutOfDate()` method for video editor, which determines if the video src is referring to the current lang's asset folder when it should be referring to the shared assets folder
    - This is used to call `saveChanges()` when there have been no changes made to the panel
- Added `assetsOutOfDate()` method for image editor, which determines if any image src is referring to the current lang's asset folder when it should be referring to the shared assets folder
    - This is used to call `saveChanges()` when there have been no changes made to the panel
- Uploaded logo to shared assets folder rather than the current lang's assets folder

### Notes
- When deleting an asset and its source count hits 0, it gets removed from `configFileStructure`. However the asset doesn't get removed from the assets folder of the product. Due to this, when the app is reloaded and `configFileStructure` is initialized, the deleted asset returns. If this is a bug, I can open a new issue for this. 
- Once this PR is finalized and merged, I can begin working on #213. When copying slides from one languages config to another, my idea is to remove all of the assets from the current language's asset folder, and add them to the shared assets folder. Then the slides copied over will reference assets from the shared assets folder
- console logs are just for testing, will be removed before merging

### Testing

#### Creating product
1. Create a new storylines product and fill in necessary metadata. Be sure to include a logo
2. Click Next
3. Press F12, and observe that, within the console, `configFileStrucuture` stores the logo within the `assets/shared` folder
4. Check the `en` and `fr` configs, and observe that the introSlide has a `src` value for its logo that refers to the `assets/shared` folder

#### Adding an asset to configs of both langs
5. Within the `en` config, create a new slide, and then an image panel within it
6. Create an image panel within it
7. Upload an image
8. Observe, in the console, that `configFileStrucuture` stores the asset within the `assets/en` folder
9. Click `save changes`
10 Switch to the `fr` config
11. Create new slide, and then an image panel within it
12. Upload the exact same image that you uploaded in the `en` config
13. Observe, in the console, that `configFileStrucuture` stores the asset within the `assets/shared` folder, and has removed it from the `assets/en` folder
14. Switch back to the `en` config
15. Go to the slide containing the image you uploaded, and go to the advanced editor
16. Observe that the src of the asset within the image panel now refers to the `assets/shared` folder

#### Deleting an asset with a source count greater than 1
17. Within the `en` config, delete the image that you uploaded
18. Observe, in the console, that the image still exists in `configFileStructure` within the `assets/shared` folder (since its source count has gone from 2 to 1)
19. Click `save changes` 

#### Deleting an asset with a source count of 1
20. Switch over to the `fr` config
21. Delete the image that you uploaded here
22. Observe, in the console, that the image now doesn't exists within the `assets/shared` folder (since its source count has gone from 1 to 0)
23. Click `save changes`

#### Changing the type of a panel that contains assets from shared assets folder
24. Upload a (new) image to the `en` and `fr` configs
25. Click `save changes`
26. Within one config, switch the panel type of the image panel
27. Observe, in the console, that the image still exists within the `assets/shared` folder (since its source count has gone from 2 to 1)
28. Observe, in the advanced editor, that the image uploaded now doesn't exist
29. Click `save changes`
30. Switch to the other config, and switch the panel type of the image panel
31.  Observe, in the console, that the image now doesn't exists within the `assets/shared` folder (since its source count has gone from 1 to 0)
32. Observe, in the advanced editor, that the image uploaded now doesn't exist
33. Click `save changes`
34. Repeat the above steps, but using video panels. It should also work in the same way

2024-10-30 20:17 UTC, RyanCoulsonCA requested changes
Haven't tested the demo for this PR just yet as I'm a bit tied up with TCEI changes, but this is my first-pass review just taking a look at the code. Will test the demo tomorrow!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OAU191M8_oUQk6xXKjs:b19gumc)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/image-editor.vue` line 327 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATy04KB2yi5KW_Iy2E:-OATy04KB2yi5KW_Iy2F:b-3gyugi) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L327)):*
> this.configFileStructure.assets['shared'].file(this.imagePreviews[idx].id) ? 'shared' : this.lang

This is used both here and in the `const fileSource` line assignment above, it may be worth assigning it to it's own variable at the top of the code block to prevent code duplication.
___
*[`src/components/image-editor.vue` line 351 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATwSqh7VNoEyHV3fPl:-OATwSqh7VNoEyHV3fPm:b-x3wn9f) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L351)):*
> ```Vue
>             console.log('imagePreviews');
>             console.log(JSON.parse(JSON.stringify(this.imagePreviews)));
>             for (let i = 0; i < this.panel.items.length; i++) {
> ```

If we don't need to use the item index for anything, I'm thinking we can just use the following to save a couple of lines:
```js 
for(asset in this.panel.items) {
  const assetSrc = asset.src.split('/');
  ...
}
```
___
*[`src/components/image-editor.vue` line 358 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATwxV72yMtAOK0ug5m:-OATwxV72yMtAOK0ug5n:b-45eoyo) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L358)):*
> ```Vue
>                 const assetFolder = assetSrc[2];
>                 const assetId = assetSrc[3];
>                 if (this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared') {
> ```

You can just use the following here:

```js
return this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared';
```
___
*[`src/components/image-editor.vue` line 372 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATx8MF1wg1auxTCo9q:-OATx8MF1wg1auxTCo9r:ba4o3tc) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L372)):*
> ```Vue
>             const assetFolder = assetSrc[2];
>             const assetId = assetSrc[3];
>             if (this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared') {
> ```

Same as above, you can just use this here:
```js
return this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared'
```
___
*[`src/components/image-editor.vue` line 425 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATyzQE6UwfQqOad0Gm:-OATyzQE6UwfQqOad0Gn:b7o1xqb) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L425)):*
> this.configFileStructure.assets['shared'].file(imageFile.id) ? 'shared' : this.lang

Same as before, since this is used multiple times (here and in the `else` block below), it may be worth assigning it earlier to reduce code duplication.
___
*[`src/components/metadata-editor.vue` line 879 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU-i85-mP-725X_XzH:-OAU-i85-mP-725X_XzI:b-kafufu) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/metadata-editor.vue#L879)):*
> ```Vue
> 
>         // If uploadLogo is set, upload the logo to the directory.
>         // Q: if we create a shared assets folder, should the logo just go there, since both langs
> ```

Someone can shut me down if I'm wrong here, but I don't know if we should necessarily assume that the logo will be the same for both products. The best example I can think of would be if the product logo has some sort of text in it and the author wants to have an English and a French version of it.

I'm not sure how common of a case that would be though. It may be worth a discussion at some point.
___
*[`src/components/video-editor.vue` line 333 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU1UtV-7VomXHqiBsF:-OAU1UtV-7VomXHqiBsG:bhq4njz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/video-editor.vue#L333)):*
> this.configFileStructure.assets['shared'].file(this.videoPreview.id) ? 'shared' : this.lang

Same as the image file, this should probably be stored assigned to a variable earlier to prevent code duplication.
___
*[`src/components/video-editor.vue` line 377 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU1hU64UdpxbMf0VpK:-OAU1hU64UdpxbMf0VpL:bjr34lz) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/video-editor.vue#L377)):*
> ```Vue
>             // An assets src value is "out of date" if the asset exists in the shared asset folder, but still
>             // references the curr lang's assets folder
>             if (this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared') {
> ```

```js
return this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared'
```
___
*[`src/components/video-editor.vue` line 407 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU1ox13QCQPXDUo_vt:-OAU1ox13QCQPXDUo_vu:b-2e9313) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/video-editor.vue#L407)):*
> this.configFileStructure.assets['shared'].file(this.videoPreview.id) ? 'shared' : this.lang

Same as the previous comments about this!


<!-- Sent from Reviewable.io -->

2024-10-31 17:13 UTC, szczz requested changes
>When deleting an asset and its source count hits 0, it gets removed from `configFileStructure`. However the asset doesn't get removed from the assets folder of the product. Due to this, when the app is reloaded and `configFileStructure` is initialized, the deleted asset returns. If this is a bug, I can open a new issue for this.

This seems like a bug to me. We don't want stale assets floating around in storylines products. Someone please correct me if I'm wrong and missing a use case for this. 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OAYYm-wBAL_rlJRbzCB:bzidcz7)* status: all files reviewed, 10 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[`src/components/image-editor.vue` line 225 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAYXTf8-7KiKrqwJBq0:-OAYXTf8-7KiKrqwJBq1:b2orb1x) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L225)):*
> ```Vue
>             oppositeSourceCount = this.sourceCounts[oppositeFileSource] ?? 0;
>             this.sourceCounts[oppositeFileSource] = 0;
>             this.configFileStructure.assets[oppositeLang].remove(file.name);
> ```

I think we need to perform this on this.lang's folder. While following the PR test steps, I noticed that the img remains in the original langs asset folder after it has been moved to the shared folder. 

Scenario "Adding an asset to configs of both langs" indicates that the image should be removed from the assets/en folder, however, it persists. 
___
*[`src/components/metadata-editor.vue` line 879 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU-i85-mP-725X_XzH:-OAYYSQu4uyI75VpggCn:bzahgee) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/metadata-editor.vue#L879)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Someone can shut me down if I'm wrong here, but I don't know if we should necessarily assume that the logo will be the same for both products. The best example I can think of would be if the product logo has some sort of text in it and the author wants to have an English and a French version of it.

I'm not sure how common of a case that would be though. It may be worth a discussion at some point.
</blockquote></details>

Agreed and I think that will be a relatively common case. 


<!-- Sent from Reviewable.io -->

2024-10-31 19:32 UTC, RyanCoulsonCA requested changes
> When deleting an asset and its source count hits 0, it gets removed from `configFileStructure`. However the asset doesn't get removed from the assets folder of the product. Due to this, when the app is reloaded and `configFileStructure` is initialized, the deleted asset returns. If this is a bug, I can open a new issue for this.

If I'm understanding this correctly, it's probably this same issue we've had for a while. See the following: https://github.com/ramp4-pcar4/storylines-editor/issues/343, https://github.com/ramp4-pcar4/storylines-editor/issues/111

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OAZ1buw4uLSIpWK8Qsh:brvktdq)* status: all files reviewed, 11 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/image-editor.vue` line 221 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAYx8Cf545Nt5fPeJG9:-OAYx8Cf545Nt5fPeJGA:bcokl9i) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L221)):*
> ```Vue
>         // in the shared nor the opposite langs assets folder, the file should be uploaded to the current
>         // langs assets folder
>         if (this.configFileStructure.assets[oppositeLang].file(file.name)) {
> ```

I've found a bug that most likely relates to this section. Try out these steps:

1. Create a new image panel using the English configuration.
2. Upload an image.
3. Save the product.
4. Swap to the French configuration and create a new image panel.
5. Upload the same image you uploaded to the English slide.
6. Save the product.

The image is correctly moved to the `shared` folder, however, the image source for the panel in the English configuration still references the `en` folder when it should be referencing the `shared` folder.

This block will need additional code that updates the source path in the opposite language config with the new `shared` path. It looks like the video editor is missing this too, so we'll need there too.


<!-- Sent from Reviewable.io -->

2024-11-01 20:24 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: all files reviewed, 11 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/image-editor.vue` line 351 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATwSqh7VNoEyHV3fPl:-OAdNvCL1i7I0cDYlTsJ:b-uyzha6) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L351)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

If we don't need to use the item index for anything, I'm thinking we can just use the following to save a couple of lines:
```js 
for(asset in this.panel.items) {
  const assetSrc = asset.src.split('/');
  ...
}
```
</blockquote></details>

In hindsight, I don't think it actually works as I've written it here. You can ignore it, or `this.panel.items.forEach(asset => { ... });` should work.


<!-- Sent from Reviewable.io -->

2024-11-04 18:48 UTC, IshavSohal reviewed
Yeah that's exactly what I was referring to

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OAsRt2D9GWy8rNbTWgK:b-j1ives)* status: 2 of 7 files reviewed, 11 unresolved discussions (waiting on @RyanCoulsonCA and @szczz)

___
*[`src/components/image-editor.vue` line 221 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAYx8Cf545Nt5fPeJG9:-OAsS3dkBOBO5xE24dPJ:b-l4dcf9) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L221)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I've found a bug that most likely relates to this section. Try out these steps:

1. Create a new image panel using the English configuration.
2. Upload an image.
3. Save the product.
4. Swap to the French configuration and create a new image panel.
5. Upload the same image you uploaded to the English slide.
6. Save the product.

The image is correctly moved to the `shared` folder, however, the image source for the panel in the English configuration still references the `en` folder when it should be referencing the `shared` folder.

This block will need additional code that updates the source path in the opposite language config with the new `shared` path. It looks like the video editor is missing this too, so we'll need there too.
</blockquote></details>

I ended up creating a `shared-asset` event, which is emitted whenever an asset is to be moved to the shared assets folder. The handler for this event will look for each instance of the uploaded asset within the opposite lang's config, and will update its source to refer to the shared asset folder. Is this the approach you had in mind? Let me know if you still have this bug. 
___
*[`src/components/image-editor.vue` line 225 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAYXTf8-7KiKrqwJBq0:-OAsSUgF9Vx2oUbP--nu:b-n1l0dm) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L225)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

I think we need to perform this on this.lang's folder. While following the PR test steps, I noticed that the img remains in the original langs asset folder after it has been moved to the shared folder. 

Scenario "Adding an asset to configs of both langs" indicates that the image should be removed from the assets/en folder, however, it persists.
</blockquote></details>

I think this may be related to the bug I mentioned (the assets not being deleted from the product in the server). Whenever the product is re-fetched from the server, `configFileStructure` gets updated such that it contains any/all deleted assets. 

If the product is not re-fetched from the server, this issue shouldn't occur, but correct me if I'm wrong.  
___
*[`src/components/image-editor.vue` line 327 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATy04KB2yi5KW_Iy2E:-OAsT1vk0fS2sZ6__A4t:b2tpwxa) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L327)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

> this.configFileStructure.assets['shared'].file(this.imagePreviews[idx].id) ? 'shared' : this.lang

This is used both here and in the `const fileSource` line assignment above, it may be worth assigning it to it's own variable at the top of the code block to prevent code duplication.
</blockquote></details>

Donethanks, I created a method `srcFolder()` to do this
___
*[`src/components/image-editor.vue` line 351 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATwSqh7VNoEyHV3fPl:-OAsTAkrBszPZBqDYY9a:bikqny) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L351)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

In hindsight, I don't think it actually works as I've written it here. You can ignore it, or `this.panel.items.forEach(asset => { ... });` should work.
</blockquote></details>

Due to the new `shared-asset` event this method isn't needed anymore, so I just deleted it. 
___
*[`src/components/image-editor.vue` line 358 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATwxV72yMtAOK0ug5m:-OAsTKrJ6-6xHUCnY2i6:b4tguxp) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L358)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

You can just use the following here:

```js
return this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared';
```
</blockquote></details>

Deleted this method, all good now
___
*[`src/components/image-editor.vue` line 372 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATx8MF1wg1auxTCo9q:-OAsU2nZ16ZgJVNra1I1:b4tguxp) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L372)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Same as above, you can just use this here:
```js
return this.configFileStructure.assets['shared'].file(assetId) && assetFolder !== 'shared'
```
</blockquote></details>

Deleted this method, all good now
___
*[`src/components/image-editor.vue` line 425 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATyzQE6UwfQqOad0Gm:-OAsUAVS8TARr5thT7Gw:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L425)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

> this.configFileStructure.assets['shared'].file(imageFile.id) ? 'shared' : this.lang

Same as before, since this is used multiple times (here and in the `else` block below), it may be worth assigning it earlier to reduce code duplication.
</blockquote></details>

Donethanks
___
*[`src/components/metadata-editor.vue` line 879 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU-i85-mP-725X_XzH:-OAsTbSB2OxGXnuZgzfN:bo9s5pi) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/metadata-editor.vue#L879)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Agreed and I think that will be a relatively common case.
</blockquote></details>

Ah fair point. However upon creating a product, both configs now have a `src` for their respective logos that refers to the `assets/en` folder. 
___
*[`src/components/video-editor.vue` line 333 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU1UtV-7VomXHqiBsF:-OAsUD414vVvqn2bELUl:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/video-editor.vue#L333)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

> this.configFileStructure.assets['shared'].file(this.videoPreview.id) ? 'shared' : this.lang

Same as the image file, this should probably be stored assigned to a variable earlier to prevent code duplication.
</blockquote></details>

Donethanks
___
*[`src/components/video-editor.vue` line 377 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OAU1hU64UdpxbMf0VpK:-OAsUQ7YBevuBI8lk_Hk:b4tguxp) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/video-editor.vue#L377)):*
<details><summary><i>Previously, R [...]

2024-11-22 16:58 UTC, RyanCoulsonCA requested changes
> Reviewed 2 of 6 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @IshavSohal and @szczz)

___
*[`src/components/editor.vue` line 218 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCJgxq87yQ7dG1H2es1:-OCJgxq87yQ7dG1H2es2:b-aqarlv) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/5844a963cdb3d1942f54cbcf35baa9e847cc03d4/src/components/editor.vue#L218)):*
> Is this the approach you had in mind?

I think this approach should work :thumbsup: 
___
*[`src/components/editor.vue` line 229 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCJhMv0C2cJEHtA5ULQ:-OCJhMv0C2cJEHtA5ULR:blb3f7v) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/5844a963cdb3d1942f54cbcf35baa9e847cc03d4/src/components/editor.vue#L229)):*
> ```Vue
>         console.log(JSON.parse(JSON.stringify(oppositeConfig.slides)));
> 
>         for (let i = 0; i < oppositeConfig.slides.length; i++) {
> ```

This (and the `panel` loop just below this) can be simplified with something like the following:

```js
oppositeConfig.slides.forEach(oppositeSlide => { ... });
```

The variable `oppositeSlide` can be changed to whatever you think works!
___
*[`src/components/editor.vue` line 239 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCJhprGB7kDGK_goLCV:-OCJhprGB7kDGK_goLCW:b-3lkibf) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/5844a963cdb3d1942f54cbcf35baa9e847cc03d4/src/components/editor.vue#L239)):*
> ```Vue
>                 console.log(JSON.parse(JSON.stringify(currPanel)));
> 
>                 // if panel is slideshow, image or video then proceed
> ```

This will miss the `dynamic` panel, which like slideshows can have any slide type as a child (including slideshows).

It may be nice to use a recursive solution here like we use in other parts of the app in order to reduce code duplication (see an example [here](https://github.com/ramp4-pcar4/storylines-editor/blob/main/src/components/metadata-editor.vue#L784), although we can simplify it). 

The recursive function would look something like the following (disclaimer: wrote this directly in Reviewable and haven't tested it so it may have some syntax errors or bugs):

```js
const recursiveHelper = (panel: BasePanel) => {
  switch (panel.type) {
    case 'slideshow':
      panel.items.forEach(item => recursiveHelper(item));
      break;
    case 'dynamic':
      panel.children.forEach(child => recursiveHelper(child));
      break;
    default:
      // your code to handle the individual panels here.
      // If we want to ensure this only runs on images and videos, we can add a check for that here too.
      break;
  }
}
```

After you have this, you should just need to call it like this:
```js
currSlide.panel.forEach(panel => { recursiveHelper(panel); }
```


<!-- Sent from Reviewable.io -->

2024-11-26 20:47 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @RyanCoulsonCA and @szczz)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCeC0kT8e76WOlaSLJr:-OCeC0kT8e76WOlaSLJs:b-jbw7is) (no related file):*
I've made one additional change. With the new redesigns merged in,  I noticed that the `configLang` prop was not updating appropriately when changing from the `en` config to the `fr` config (since they now both reside in the same editor view). I've created a new `lang-change` event that is emitted whenever a `slide-change` event is handled by the `editor` component. The `lang-change` event is handled in the `metadata-editor` component. 
___
*[`src/components/editor.vue` line 229 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCJhMv0C2cJEHtA5ULQ:-OCeBvqk2HwHHHBXd-9t:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/5844a963cdb3d1942f54cbcf35baa9e847cc03d4/src/components/editor.vue#L229)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This (and the `panel` loop just below this) can be simplified with something like the following:

```js
oppositeConfig.slides.forEach(oppositeSlide => { ... });
```

The variable `oppositeSlide` can be changed to whatever you think works!
</blockquote></details>

Donethanks
___
*[`src/components/editor.vue` line 239 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCJhprGB7kDGK_goLCV:-OCeBxKbC67QIlEYLhWu:b-5a2h77) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/5844a963cdb3d1942f54cbcf35baa9e847cc03d4/src/components/editor.vue#L239)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This will miss the `dynamic` panel, which like slideshows can have any slide type as a child (including slideshows).

It may be nice to use a recursive solution here like we use in other parts of the app in order to reduce code duplication (see an example [here](https://github.com/ramp4-pcar4/storylines-editor/blob/main/src/components/metadata-editor.vue#L784), although we can simplify it). 

The recursive function would look something like the following (disclaimer: wrote this directly in Reviewable and haven't tested it so it may have some syntax errors or bugs):

```js
const recursiveHelper = (panel: BasePanel) => {
  switch (panel.type) {
    case 'slideshow':
      panel.items.forEach(item => recursiveHelper(item));
      break;
    case 'dynamic':
      panel.children.forEach(child => recursiveHelper(child));
      break;
    default:
      // your code to handle the individual panels here.
      // If we want to ensure this only runs on images and videos, we can add a check for that here too.
      break;
  }
}
```

After you have this, you should just need to call it like this:
```js
currSlide.panel.forEach(panel => { recursiveHelper(panel); }
```
</blockquote></details>

Donethanks, appreciate the help!


<!-- Sent from Reviewable.io -->

2024-12-04 18:32 UTC, RyanCoulsonCA requested changes
> Reviewed 5 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @szczz)

___
*[`server/index.js` line 12 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-ODHw-Mt3II87xnCocAk:-ODHw-Mt3II87xnCocAl:baa49t0) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/0006581cbe51b81dd6e1f45b9df2dbf4a9fb1d31/server/index.js#L12)):*
> ```JavaScript
> const simpleGit = require('simple-git');
> const responseMessages = [];
> require('dotenv').config();
> ```

I think this file snuck into this PR somehow! Other than that, all of the test I've done look good!


<!-- Sent from Reviewable.io -->

2024-12-10 22:34 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA and @szczz)

___
*[`server/index.js` line 12 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-ODHw-Mt3II87xnCocAk:-ODmgyTxAvPGnekeGASA:b-rhtruj) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/0006581cbe51b81dd6e1f45b9df2dbf4a9fb1d31/server/index.js#L12)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I think this file snuck into this PR somehow! Other than that, all of the test I've done look good!
</blockquote></details>

This was just me fixing some formatting issues I noticed. Everything should be working the same as before. 


<!-- Sent from Reviewable.io -->

2024-12-13 16:38 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 7 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: all files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @szczz)

___
*[`server/index.js` line 12 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-ODHw-Mt3II87xnCocAk:-OE-sg0_3yiyLgCgqYq2:b4c9lyr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/0006581cbe51b81dd6e1f45b9df2dbf4a9fb1d31/server/index.js#L12)):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

This was just me fixing some formatting issues I noticed. Everything should be working the same as before.
</blockquote></details>

:thumbsup: 


<!-- Sent from Reviewable.io -->

2024-12-13 17:11 UTC, szczz requested changes
#### Adding an asset to configs of both langs

After performing these steps, but with a slight modification of copying the config from the en slide. The assets still remain in the en folder. They get moved to the shared folder if you manually add the same image to the FR slide though.

> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OE-z3_cASd6P4rEcAQo:bmep66x)* status: all files reviewed, 2 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[`server/index.js` line 12 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-ODHw-Mt3II87xnCocAk:-ODlstpz65BA8qXe6jd2:bkgk8fy) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/0006581cbe51b81dd6e1f45b9df2dbf4a9fb1d31/server/index.js#L12)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

I think this file snuck into this PR somehow! Other than that, all of the test I've done look good!
</blockquote></details>

Yep please remove this file from the PR


<!-- Sent from Reviewable.io -->

2024-12-23 21:56 UTC, IshavSohal reviewed
Donethanks. As I was making the fix for this, I decided to create a helper method, `panelHelper()`, which can be provided a callback (as well as additional arguments for it) to be called on each ImagePanel/VideoPanel within a given BasePanel. This may be a bit overkill, so let me know your thoughts/opinions. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OEpR4kJE9BjpH8HfDqv:b-gtmzkt)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @szczz)

___
*[`server/index.js` line 12 at r3](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-ODHw-Mt3II87xnCocAk:-OEpR1bz-cwyPm1WvZgs:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/0006581cbe51b81dd6e1f45b9df2dbf4a9fb1d31/server/index.js#L12)):*
<details><summary><i>Previously, szczz (Matt Szczerba) wrote…</i></summary><blockquote>

Yep please remove this file from the PR
</blockquote></details>

Donethanks


<!-- Sent from Reviewable.io -->

2025-01-14 18:02 UTC, RyanCoulsonCA requested changes
> Reviewed 4 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @IshavSohal and @szczz)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCeC0kT8e76WOlaSLJr:-OG_xyxP6JAw4i-b8Kjr:b-6njivp) (no related file):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

I've made one additional change. With the new redesigns merged in,  I noticed that the `configLang` prop was not updating appropriately when changing from the `en` config to the `fr` config (since they now both reside in the same editor view). I've created a new `lang-change` event that is emitted whenever a `slide-change` event is handled by the `editor` component. The `lang-change` event is handled in the `metadata-editor` component.
</blockquote></details>

Found a bug:

1. Create a new blank slide.
2. Change both the English and French slide to an "image" slide.
3. Upload a photo to the English slide.
4. Upload the same photo to the French slide.
5. Switch back to the English slide and notice that the image doesn't appear. Switching over to the Advanced panel shows that the `src` still points to the `en` folder instead of `shared`.

This seems to work fine for slideshow panels, just breaks with image panels.


<!-- Sent from Reviewable.io -->

2025-01-14 19:03 UTC, yileifeng reviewed
Note: loading in existing products with old configuration asset folder structure will freeze the metadata page and eventually resolve with all N/A values. This breaks backwards compatibility and should be considered before merging without a plan in place to migrate old products.

> Reviewed 1 of 6 files at r1, 2 of 7 files at r3, 1 of 3 files at r4, 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OGa5dAADvMaBz3BVIx0:bq3d0g3)* status: all files reviewed, 2 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/image-editor.vue` line 130 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OATn-er4wesariRl3DN:-OATn-er4wesariRl3DO:b-2dr7hi) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4e47d8b5f3847d233377a64056299aa9d33d6c68/src/components/image-editor.vue#L130)):*
> ```Vue
> 
>     mounted(): void {
>         console.log('');
> ```

Blocker for console logs


<!-- Sent from Reviewable.io -->

2025-01-14 21:05 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OCeC0kT8e76WOlaSLJr:-OGacRBf7h5McoMQM-xS:b-d8zw1m) (no related file):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Found a bug:

1. Create a new blank slide.
2. Change both the English and French slide to an "image" slide.
3. Upload a photo to the English slide.
4. Upload the same photo to the French slide.
5. Switch back to the English slide and notice that the image doesn't appear. Switching over to the Advanced panel shows that the `src` still points to the `en` folder instead of `shared`.

This seems to work fine for slideshow panels, just breaks with image panels.
</blockquote></details>

Donethanks, should be all good now


<!-- Sent from Reviewable.io -->

2025-01-16 22:34 UTC, IshavSohal reviewed
This may have been due to the console logs that I've now removed, which were problematic for large products.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OGlElZl-XGm9K0g1pva:b-fefdeu)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OGlEjk55tWqE1N9Ct2U:-OGlEjk65SiJVhpR5Jqo:b1vwyqa) (no related file):*
Removed all console logs.


<!-- Sent from Reviewable.io -->

2025-01-17 15:56 UTC, szczz requested changes
Couple of issues: 

1. If you create a new storyline, upload a logo to the EN config and then save it, the logo gets added to the en assets folder as expected. If you return to the dashboard and load the storyline and then change to the french config, the original logo remains. If you go to the editor page and then press save, it results in the logo being stored in both the en fold and fr folder even though its exactly the same.

2. If you create a new slide and upload an image with the name "test.jpeg" in the en config, then flip to the fr config and upload a different image with the name "test.jpeg", returning to the en config will display the second image. If you save the en config before the french one, the second image will show up in the shared folder, but the first image will remain in the en folder. Perhaps a hash function or looking at image metadata could help handle this situation. 
 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OGow2TZ4G-Ni7rH8NDN:b885t7t)* status: 1 of 10 files reviewed, 3 unresolved discussions (waiting on @IshavSohal, @RyanCoulsonCA, and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-23 19:35 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 0 of 13 files reviewed, 4 unresolved discussions (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OHJb-zf8vhuBSn0HEnR:-OHJb-zf8vhuBSn0HEnS:b-osjsq4) (no related file):*
I have a few questions regarding how to proceed: 

When should we consider two asset files to be the same? Should it be when both their names and contents are the same, or when only their contents are the same? Currently I compare using both names and contents, but I'm running into some issues.

Should we expect assets to be in nested subfolders within the asset folders (like in the 0000... product)? Currently I'm doing this, but not sure if this is unnecessary. 


<!-- Sent from Reviewable.io -->

2025-01-27 16:07 UTC, IshavSohal commented
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Comparing file content to determine equality seems reasonable IMO. However, what would the naming convention of the shared asset file be in this situation?
</blockquote></details>

There are a few edge cases when comparing just file contents:

- Suppose there exists an asset, `test.png` in the `en` folder
- If you try to upload an asset `test2.png` with the same contents as `test.png` into the `en` config, then `test.png` would be used as the src, meaning that `test2.png` would not be uploaded to the `en` folder
- If you try to upload an asset `test.png` with different contents than the original `test.png` into the `en` config, we would have to upload this asset into the `en` folder using a unique name, like `test(2).png`

When comparing both contents and names, however, there are many more edge cases. Are there any use cases in which the user would purposely want two files with the same content but different names?


<!-- Sent from Reviewable.io -->

2025-01-31 17:05 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OHxIv7w8aDMHMgCUR8a:-OHxIv7w8aDMHMgCUR8b:b-c1a0qf) (no related file):*
There seems to be quite a bit of repetition regarding the code responsible for comparing files. Would it be a good idea to encapsulate these methods in a plugin? If so, should we wait until we migrate over to the Composition API?


<!-- Sent from Reviewable.io -->

2025-01-31 19:15 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: all files reviewed, 4 unresolved discussions (waiting on @IshavSohal, @RyanCoulsonCA, and @szczz)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OHxIv7w8aDMHMgCUR8a:-OHxldBRCOOOBopwhcOB:b-fj4a61) (no related file):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

Will always advocate for prioritizing the code refactor/composition API migration. Maybe a patch solution for this PR (if not too difficult to implement) is to add a composable: https://vuejs.org/guide/reusability/composables.
</blockquote></details>

As a follow up, it does not make much sense to implement the composables approach if it will just be overwritten later. I would say it's fine to hold off on that implementation for now but it can be worth considering as an option in the refactor. It makes much more sense to merge this PR before starting on composition API / Pinia work.


<!-- Sent from Reviewable.io -->

2025-02-03 22:32 UTC, IshavSohal reviewed
Now, when a new product is created, the logo is uploaded into the `shared` asset folder, since the config of the current lang is copied over to the opposite lang's config. However, if the user wants to change the logo for a specific lang's config, the asset uploaded will be added into that lang's asset folder (unless it already exists in the opposite lang's asset folder, in which case it gets uploaded to the `shared` folder)

Also, when the asset uploaded has the same name as an existing asset, the hashes of the two assets will be compared to ensure we are not uploading the same asset again. If the two assets have different content, however, the uploaded asset will be assigned a unique name to prevent overwriting the existing asset. As @yileifeng mentioned, it may be a good idea to allow the user to choose between creating their own unique name and overwriting the existing asset, so I'm going to try to get that working. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OICu_T376s83YpH4r0v:bmu77mu)* status: all files reviewed, 4 unresolved discussions (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OHJb-zf8vhuBSn0HEnR:-OICrpFK569o3XUWcXQw:b-uz7krd) (no related file):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

This PR is growing increasingly large as we attempt to handle a fairly rare case which is a mild concern, we can always spinoff issues that refine niche cases for the feature. Thinking about it more, this would be my opinion for the following cases: 
1. Different file names - *always upload new file to assets folder* since it could be unexpected behavior for users to find their new file `test2.png` to not be added

This way we can also save a ton of computation time as we would only need to compare file contents when a newly uploaded file contains the same name.  I'm not really sure why this would be an actual use case but maybe if user wanted to upload the same image to different sections of the Storyline with different labels for clarity (e.g. intro_logo.png and slide3_logo.png). 

2. Same file names - this is the case when we compare file contents to avoid duplication and also addresses Matt's found bug

In this case, when the file contents differ an option is to prompt the users to rename or overwrite(?) the new file. Let me know if this overall approach makes sense or what might not work.
</blockquote></details>

Yeah this is how I'm currently doing it. I only compare the hashes of two asset files when they have the same name. If the asset uploaded shares a name with no other asset in any asset folder, it gets uploaded right away, without hashing any files. However, the name of the uploaded image would have to be compared with the names of all assets in each of the assets folder in this case, which could be time consuming. I'm not sure if we can really avoid this though.

Prompting the user to rename the uploaded asset seems like an interesting idea. Currently when the asset uploaded has the same name but different content as an existing asset, the asset uploaded gets a number (ex. `test(2).png`) appended to its name to ensure it's unique. This could potentially confuse users. I'll try giving this a shot.

Also, once the repetitive code is moved into its own plugin/composable, the size of this PR will reduce by ~300-400 lines. 


<!-- Sent from Reviewable.io -->

2025-02-05 17:42 UTC, IshavSohal commented
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Yeah this is how I'm currently doing it. I only compare the hashes of two asset files when they have the same name. If the asset uploaded shares a name with no other asset in any asset folder, it gets uploaded right away, without hashing any files. However, the name of the uploaded image would have to be compared with the names of all assets in each of the assets folder in this case, which could be time consuming. I'm not sure if we can really avoid this though.

Prompting the user to rename the uploaded asset seems like an interesting idea. Currently when the asset uploaded has the same name but different content as an existing asset, the asset uploaded gets a number (ex. `test(2).png`) appended to its name to ensure it's unique. This could potentially confuse users. I'll try giving this a shot.

Also, once the repetitive code is moved into its own plugin/composable, the size of this PR will reduce by ~300-400 lines.
</blockquote></details>

On second thought, I think it may be a better idea to save the additional feature (prompting user for new asset name) for another time, as it makes the code even more complicated. I think the current convention (adding a number to end of asset name) should be fine for the time being. 

I'll probably log a new issue once this PR is finalized and merged. 


<!-- Sent from Reviewable.io -->

2025-02-06 15:12 UTC, yileifeng approved these changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 7 of 13 files reviewed, 5 unresolved discussions (waiting on @IshavSohal, @RyanCoulsonCA, and @szczz)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OHJb-zf8vhuBSn0HEnR:-OIQo1sk-i6Tzvy0TDwW:b-fox8nq) (no related file):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

On second thought, I think it may be a better idea to save the additional feature (prompting user for new asset name) for another time, as it makes the code even more complicated. I think the current convention (adding a number to end of asset name) should be fine for the time being. 

I'll probably log a new issue once this PR is finalized and merged.
</blockquote></details>

All cases seem to be working well when testing :+1:
___
*[`src/components/image-editor.vue` line 295 at r12](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OIQoFP--gZXuwKMeAer:-OIQoFP--gZXuwKMeAes:bdfybr7) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/a3cf5507d87bd5741299fc0560ebd41dd9bd9ee6/src/components/image-editor.vue#L295)):*
> ```Vue
>             // Only compare the hashes of two files when they have the exact same name
>             if (assetName === file.name) {
>                 console.log('current image has same name as uploaded image');
> ```

Reminder to cleanup console logs all before merging


<!-- Sent from Reviewable.io -->

2025-02-10 18:59 UTC, szczz approved these changes
:trophy: 

> Reviewed 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-:-OIlDjTwDaPdm2fd7zMe:b-fnwc0l)* status: all files reviewed, 4 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-02-12 22:08 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 8 of 13 files reviewed, 5 unresolved discussions (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OIwBOJl4sGJuOi45Gqq:-OIwBOJl4sGJuOi45Gqr:bdorymn) (no related file):*
Removed all comments. Also integrated the new background image feature with the shared asset system. It seems to be working well on my end, but maybe try testing that out before merging. 


<!-- Sent from Reviewable.io -->

2025-02-13 18:37 UTC, yileifeng approved these changes
> Reviewed 5 of 5 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: all files reviewed, 4 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)

___
*[a discussion](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OIwBOJl4sGJuOi45Gqq:-OJ-aEcq1H5IJpHeY6qz:bnfp4nl) (no related file):*
<details><summary><i>Previously, IshavSohal (Ishav Sohal) wrote…</i></summary><blockquote>

Removed all comments. Also integrated the new background image feature with the shared asset system. It seems to be working well on my end, but maybe try testing that out before merging.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>


<!-- Sent from Reviewable.io -->

2025-02-18 20:16 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: 8 of 13 files reviewed, 7 unresolved discussions (waiting on @mohsin-r, @RyanCoulsonCA, and @yileifeng)

___
*[`src/components/editor.vue` line 537 at r13](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OJJUXTGBxDp6uXR_Aky:-OJPgu0HBGdBYmahW_Jt:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/34cc56612981fde3e38499668d30d9e28068c681/src/components/editor.vue#L537)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

This line can be shortened to `const newLang = lang || this.configLang || 'en'`
</blockquote></details>

Donethanks
___
*[`src/components/image-editor.vue` line 285 at r13](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414#-OJJVO1L56wno_AI2w8o:-OJPgv6QB_0FPWc28cH-:behjw3g) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/34cc56612981fde3e38499668d30d9e28068c681/src/components/image-editor.vue#L285)):*
<details><summary><i>Previously, mohsin-r (Mohsin Reza) wrote…</i></summary><blockquote>

Curious which part of this method is `async`. Don't see any `await`s below unless there's one missing.
</blockquote></details>

Good catch, donethanks


<!-- Sent from Reviewable.io -->

2025-02-20 15:41 UTC, mohsin-r approved these changes
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/414)* status: all files reviewed, 5 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-02-21 15:59 UTC, merged