Allow height and width configuration in image panels
ramp4-pcar4/storylines-editor pull request #427
Opened 2024-11-20 21:26 UTC by gordlin

### Related Item(s)
#392 

### Changes
- [FEATURE] Add height and width fields to images in the image editor, to allow for user modification
- Add warning about maximum allowed widths

### Notes
 - New fields:

<img width="488" alt="image" src="https://github.com/user-attachments/assets/a639c40d-29a6-473a-b77d-3a3efbb11890">

 - Images try to keep their original aspect ratio, so you may not get the exact height and width you input.

### Testing
Steps:
1. Go to any product (e.g. `00000000-0000-0000-0000-000000000000`)
2. Go to any image panel. If necessary, add an image.
3. See the new height and width fields. 
    - Blank fields will make the image take up the max width according to screen size (2/3 of screen on desktop, 100% on mobile). 
    - Entering a value larger than the max width will have no effect.
    - Valid values will correctly resize the image in the preview. 
    - Try entering various values to test.

2024-11-22 20:52 UTC, RyanCoulsonCA requested changes
Works well functionally, but I think we should look in to a different way of displaying the maximum width warning as it can get a bit messy when there's more than one image:

![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/25874602/VZKeGllGO5VjEMYbDKpOxMDU/image.png)

Maybe a small information icon that displays the message when clicked like the map config editor?
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/cSpBC6_via1FQmeDna75zCRp/image.png)

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/427#-:-OCKcsTi5_HMZQoVG82C:b-s2kp5q)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-05 19:59 UTC, gordlin reviewed
Donethanks!

![image.png](https://files.reviewableusercontent.io/images/reviewable/75815453/ZBVHiCkg5DTZwERcW3Ra5Tv8/image.png)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/427#-:-ODNOt5t2slkoTI4NKRP:b-o0il66)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-05 21:53 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/427)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-05 22:05 UTC, IshavSohal approved these changes
Looks great, just make sure to rebase with main

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/427#-:-ODNqYD-1NWLDNuM6hFk:bz9sxbz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-09 22:11 UTC, gordlin reviewed
Donethanks!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/427#-:-ODhTZybCnkutcgF8APK:b-ugpthr)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @IshavSohal and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-11 14:28 UTC, merged