Create caption input for maps and charts
ramp4-pcar4/storylines-editor pull request #428
Opened 2024-11-20 21:50 UTC by IshavSohal

### Related Item(s)
#393

### Changes
- Add caption input for maps and maps

### Notes
https://github.com/ramp4-pcar4/story-ramp/pull/505 handles the map caption in the StoryRAMP repo. I will soon make a PR to handle the chart caption.

### Testing
Steps:
1. Load in a product
2. Open a slide that contains a map (or create one)
3. Within the panel containing the map, observe the input field for the caption above the map
4. Enter a caption and save changes
5. Within the product's config, observe that the map has a `caption` field with the caption you provided
6. Open a slide that contains a chart (or create one)
7. Within the panel containing the chart, observe the input field for the caption below the chart
8. Enter a caption and save changes
9. Within the product's config, observe that the chart has a `caption` field with the caption you provided

2024-11-25 21:54 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @IshavSohal)

___
*[`src/components/helpers/chart-preview.vue` line 67 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OC_JABc43YHoQokDokR:-OC_JABc43YHoQokDokS:b89li29) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/d9c51f26fad5720a807589f21b7defd7aac63413/src/components/helpers/chart-preview.vue#L67)):*
> ```Vue
>         </div>
>         <div class="flex mt-4">
>             <label :for="'chartPreviewCaption' + index" class="font-bold"
> ```

There seems to be an alignment issue with the label and the input box. We should center align the text with the input for consistency.
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/U-WzDa_bjlWUVzCtC3OAu_V2/image.png)


<!-- Sent from Reviewable.io -->

2024-11-26 21:24 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/helpers/chart-preview.vue` line 67 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OC_JABc43YHoQokDokR:-OCeM-73BXN0Sps8p876:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/d9c51f26fad5720a807589f21b7defd7aac63413/src/components/helpers/chart-preview.vue#L67)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

There seems to be an alignment issue with the label and the input box. We should center align the text with the input for consistency.
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/U-WzDa_bjlWUVzCtC3OAu_V2/image.png)
</blockquote></details>

Donethanks


<!-- Sent from Reviewable.io -->

2024-11-29 21:10 UTC, RyanCoulsonCA requested changes
> Reviewed 3 of 8 files at r1, 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @IshavSohal)

___
*[`src/components/map-editor.vue` line 36 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OCtkiWt5Ip8f6qH5gQQ:-OCtkiWt5Ip8f6qH5gQR:bg6ci3s) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4132b98d2ecc74d98ad64145613358f0f2b78036/src/components/map-editor.vue#L36)):*
> ```Vue
>                     type="text"
>                     v-model="panel.caption"
>                     placeholder="Add a caption"
> ```

This will need a translation!
___
*[`src/components/helpers/chart-preview.vue` line 75 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OCtkkM59Wj5Hm2KaNn4:-OCtkkM59Wj5Hm2KaNn5:b-iklqh7) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4132b98d2ecc74d98ad64145613358f0f2b78036/src/components/helpers/chart-preview.vue#L75)):*
> ```Vue
>                 type="text"
>                 v-model="chart.caption"
>                 placeholder="Add a caption"
> ```

Same here, needs translation


<!-- Sent from Reviewable.io -->

2024-12-02 16:09 UTC, yileifeng requested changes
![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/Fsj2-6wnW-d8jLq8o6YQbXkw/image.png)

I think vertically aligning the caption input with the text of the chart name would look nicer for the UI

> Reviewed 3 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-:-OD76kDsDc57GmgRjd5W:bkeu6ni)* status: all files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-02 21:08 UTC, spencerwahl approved these changes
> Reviewed 3 of 8 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: all files reviewed, 3 unresolved discussions (waiting on @IshavSohal and @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-03 20:43 UTC, IshavSohal reviewed
I was able to get this working, but things get a little crowded for smaller screen widths. Let me know if you prefer the way it used to look, or if you have any suggestions. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-:-ODDF-6o8gBiZoVQ0zju:b-mfr9hs)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA, @spencerwahl, and @yileifeng)

___
*[`src/components/map-editor.vue` line 36 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OCtkiWt5Ip8f6qH5gQQ:-ODDF9JfAbFQHZIKNLSW:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4132b98d2ecc74d98ad64145613358f0f2b78036/src/components/map-editor.vue#L36)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This will need a translation!
</blockquote></details>

Donethanks
___
*[`src/components/helpers/chart-preview.vue` line 75 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428#-OCtkkM59Wj5Hm2KaNn4:-ODDFDkw-GlFUR_5fxHA:bah2568) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4132b98d2ecc74d98ad64145613358f0f2b78036/src/components/helpers/chart-preview.vue#L75)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

Same here, needs translation
</blockquote></details>

Donethanks


<!-- Sent from Reviewable.io -->

2024-12-05 15:43 UTC, yileifeng approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: all files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-06 19:42 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: all files reviewed, 1 unresolved discussion (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-12-10 19:02 UTC, szczz approved these changes
> Reviewed 3 of 8 files at r1, 2 of 5 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/428)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-13 14:53 UTC, merged