Limit video upload size
ramp4-pcar4/storylines-editor pull request #430
Opened 2024-11-25 20:23 UTC by gordlin

### Related Item(s)
Issue #417 

### Changes
- [FEATURE] Prevent videos larger than 75MB from being uploaded in video panels, and show an error when attempting to upload them.

### Testing
Steps:
1. Go to any product (e.g. `00000000-0000-0000-0000-000000000000`).
2. Go to any video panel.
3. Try to upload a video greater than 75MB. It will fail and show a warning.
4. Try to upload a video less than 75MB. It will upload as expected.

2024-11-29 21:24 UTC, RyanCoulsonCA requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gordlin)

___
*[`src/components/video-editor.vue` line 204 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430#-OCtnc7yB3uMgf6Otnre:-OCtnc7z0boqQiVLDtf7:b-z9pxkj) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4645ff250a5f8cbd953feec0a4126dad97c065da/src/components/video-editor.vue#L204)):*
> ```Vue
> 
>         // Block files which are too big
>         if (file.size > this.fileSizeLimit * 1000000) {
> ```

This is nitpicky, but I believe this should be `1024 * 1024` instead of `1000000`, otherwise we'll be capping it out at slightly less than 75MB.


<!-- Sent from Reviewable.io -->

2024-12-05 20:22 UTC, gordlin reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA and @yileifeng)

___
*[`src/components/video-editor.vue` line 34 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430#-OD78GcK4FDSG1vNDvf7:-ODNU72K8PaHk6Qv5KLc:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4645ff250a5f8cbd953feec0a4126dad97c065da/src/components/video-editor.vue#L34)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/hXmJGHYNzLAFwi-UwYF0Nm1f/image.png)

Center this first line by adding a `text-align: center`
</blockquote></details>

Donethanks!
___
*[`src/components/video-editor.vue` line 204 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430#-OCtnc7yB3uMgf6Otnre:-ODNU7th0ScJJ9puchvY:b-ugpthr) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/4645ff250a5f8cbd953feec0a4126dad97c065da/src/components/video-editor.vue#L204)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This is nitpicky, but I believe this should be `1024 * 1024` instead of `1000000`, otherwise we'll be capping it out at slightly less than 75MB.
</blockquote></details>

Donethanks!


<!-- Sent from Reviewable.io -->

2024-12-06 19:33 UTC, yileifeng approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-06 19:43 UTC, RyanCoulsonCA approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-10 19:11 UTC, szczz requested changes
Just a temporary blocker as there are merge conflicts in lang.csv

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430#-:-ODlxuOzDIq5YlFCUhwQ:bquw693)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-10 19:16 UTC, gordlin reviewed
Donethanks!

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430#-:-ODlzy4L6UIRSCCtnt12:b-ugpthr)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @RyanCoulsonCA, @szczz, and @yileifeng)



<!-- Sent from Reviewable.io -->

2024-12-10 19:23 UTC, szczz approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-10 21:54 UTC, IshavSohal approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/430)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gordlin)



<!-- Sent from Reviewable.io -->

2024-12-11 15:32 UTC, merged