Disable right only toggle for dynamic slide, Remove uuid spellcheck
ramp4-pcar4/storylines-editor pull request #474
Opened 2024-11-29 19:38 UTC by IshavSohal

### Related Item(s)
#441 
#433

### Changes
- Disable the `Make the right panel the full slide` toggle for dynamic slides (i.e. for slides with only one panel)
- Disable spellcheck for the uuid entry field

### Testing
Steps:
#433
1. From the dashboard click `Load Existing Storylines Product`
2. Enter random text into the uuid field
3. Notice there is no red underline
4. Load an existing product
5. Click the change uuid link
6. Enter random text into the uuid field
7. Notice there is no red underline

#441
1. Load a product into editor-main
2. Create a new slide
3. Create a dynamic panel within this slide
4. Observe that the  `Make the right panel the full slide` toggle is disabled
5. Change the panel type, and observe that the toggle is still disabled (since the slide only contains 1 panel)

2024-12-02 16:43 UTC, RyanCoulsonCA requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @IshavSohal)

___
*[`src/components/slide-editor.vue` line 41 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-OD7ERT65bmVevs3qAJp:-OD7ERT65bmVevs3qAJq:b-80uan) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/113204221df949c4682b9970a2b61e468307f142/src/components/slide-editor.vue#L41)):*
> ```Vue
>                             class="editor-input rounded-none cursor-pointer w-4 h-4"
>                             v-model="rightOnly"
>                             :disabled="rightOnly || currentSlide.panel.length === 1"
> ```

While this does work to disable the button for dynamic panels, it's also disabling the button for any non-dynamic panel that is already full width:

![fulldisabled.gif](https://files.reviewableusercontent.io/images/reviewable/25874602/g2QNs5BohCw_QDQiHh1_LAPA/fulldisabled.gif)


<!-- Sent from Reviewable.io -->

2024-12-02 21:01 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/slide-editor.vue` line 41 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-OD7ERT65bmVevs3qAJp:-OD89gXm579vi8dxNqOV:b-39s2qx) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/113204221df949c4682b9970a2b61e468307f142/src/components/slide-editor.vue#L41)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

While this does work to disable the button for dynamic panels, it's also disabling the button for any non-dynamic panel that is already full width:

![fulldisabled.gif](https://files.reviewableusercontent.io/images/reviewable/25874602/g2QNs5BohCw_QDQiHh1_LAPA/fulldisabled.gif)
</blockquote></details>

Donethanks. Now the checkbox should be disabled when it is unchecked and the slide is already full screen, as well as when it is checked and the full screen panel is dynamic


<!-- Sent from Reviewable.io -->

2024-12-04 19:46 UTC, szczz requested changes
If you switch the slide to a dynamic slide and then change it to any other slide type, its forced to be a fullscreen panel and you can't change it unless you recreate the slide.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-ODIBtvW4B9ft6QBv0iw:bz1ltqj)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-06 21:48 UTC, IshavSohal commented
This only seems to happen if the 'make right only' checkbox was unchecked when the slide was switched to dynamic. Since the slide is a full screen slide, trying to check the 'make right only' checkbox will result in an error, regardless of the panel type. 

Would it be a good idea to check the 'make right only' checkbox upon switching a slide to dynamic?





<!-- Sent from Reviewable.io -->

2024-12-12 15:36 UTC, szczz reviewed
I think thats slightly confusing, as a user might think they can uncheck that box. We should be dynamically rendering these boxes based on the slide type.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-ODvVdX5B7bHWE55aeAy:b2uoxyh)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-19 20:14 UTC, IshavSohal reviewed
I've now made it so that the 'make right only' checkbox will not render when the panel type is dynamic. 

Additionally, when the panel type is switched, I made it so that the right only checkbox is checked if there is a full screen panel. This way, if you switch to a dynamic panel and then to another panel type, you won't be stuck with a full screen panel. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OEVX_ya3IsiatFUPUfa:bo9khjl)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @szczz)



<!-- Sent from Reviewable.io -->

2024-12-20 19:52 UTC, mohsin-r requested changes
One thing I found was that if I have a left and right panel that are both image panels and then I upload two different images to the two panels, and then I click "fullscreen panel", it shows whichever panel I am currently on (instead of the right panel as the text suggests). Additionally, suppose I get the left panel shown, then if I uncheck the "fullscreen panel" the left panel disappears and becomes text and the right panel reappears as expected. 

I'm thinking that the first switch to a full screen panel doesn't re-render the correct thing. Feel free to let me know if this is unrelated, and I'll make a new issue.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OE_aylkAqIhKn7e6aLp:b-t9ie3t)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-23 22:29 UTC, IshavSohal reviewed
I'm also able to reproduce this, but #486 will change how the full screen checkbox works, so this should be fine. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OEpcaIs9oin1NfYp5fS:b-qflyfy)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-31 14:42 UTC, yileifeng requested changes
Another case that breaks is when a product loads in with an existing full slide panel or you use the advanced editor to create a full slide panel. The "make right panel full slide" checkbox still appears for this situation and toggling it will break the slide editor. 

On a more general note, I think it is worth discussing making this full-slide functionality more intuitive for users in the future. Maybe writing up an issue to redesign all slide header options with UI/UX team guidance would be helpful. 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OFS2pPs3iZ6dMYNkyV4:b2epfiv)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-03 21:41 UTC, IshavSohal reviewed
Donethanks, this issue should now be fixed, but let me know if there are still issues.

We should probably hold off on merging this PR until #486 is merged, which I believe makes the full-slide functionality much more user-friendly. 

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OFi4ogU-GDo3gfMGMFU:b2eodpx)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mohsin-r, @RyanCoulsonCA, and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-10 16:05 UTC, mohsin-r approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-10 16:15 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-13 18:51 UTC, szczz approved these changes
Just a heads up that there's a merge conflict that needs to be resolved. 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-14 17:11 UTC, RyanCoulsonCA requested changes
Code and functionality look good, just noticed a small alignment issue with this checkbox when comparing them with the rest:
![image.png](https://files.reviewableusercontent.io/images/reviewable/25874602/roDcwhAOHxR1DbVcCA6-1kln/image.png)

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OG_mthL-fFCmA9hKH4C:b4ulaq9)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-14 20:14 UTC, IshavSohal reviewed
Donethanks, rebasing with main seems to have fixed this

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474#-:-OGaRQRI3vP6zL9JYutV:bv7yb8s)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mohsin-r, @szczz, and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-20 15:36 UTC, RyanCoulsonCA approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-20 15:53 UTC, szczz approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-20 15:53 UTC, merged