Set max width for md editor tooltip, Add untitled key, Add logo alt text to metadata
ramp4-pcar4/storylines-editor pull request #485
Opened 2024-12-06 21:24 UTC by IshavSohal

### Related Item(s)
#452 
#443 
#438

### Changes
- Set a max width of `90px` for tooltips within the `v-md-editor` component, so that a horizontal scrollbar doesn't appear when the tooltip exits the screen
- Add the `chapters.untitled` key into `lang.csv`, so that the appropriate text appears in the ToC for slides without a title
- Include the logo alt text within the metadata upon creating a new object

### Testing

Steps (#452):
1. Open a text panel
2. Decrease the screen width
3. Hover over the buttons on the right side of the editor
4. Observe that the horizontal bar doesn't appear

Steps (#443):
1. Remove the titles from one/more slide
2. Switch the ToC to horizontal
3. Open the preview
4. Observe that the title of each slide without a title (within the ToC) is 'Untitled Slide'
5. Switch to French and observe the corresponding French text in the ToC

Steps (#438):
1. Create a new product
2. Upload a logo and set the alt text
3. Click Next to proceed to the main editor page
4. Click Edit Product Metadata
6. The alt text should be visible

2024-12-16 19:33 UTC, RyanCoulsonCA requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @IshavSohal)

___
*[`src/components/text-editor.vue` line 179 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485#-OEFxLuT5CHew3URN4ah:-OEFxLuUAQyNOOfvPeDd:b-b1qqff) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/d9ed062627e491f52ec49007a38fd9bf6052e9f4/src/components/text-editor.vue#L179)):*
> ```Vue
> }
> :deep(.v-md-editor__tooltip) {
>     max-width: 90px;
> ```

This one still seems to be happening for me after the changes:
![scrollbartext.gif](https://files.reviewableusercontent.io/images/reviewable/25874602/1lAAXd6z61119WbaOpab-pFI/scrollbartext.gif)


<!-- Sent from Reviewable.io -->

2024-12-30 22:01 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)

___
*[`src/components/text-editor.vue` line 179 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485#-OEFxLuT5CHew3URN4ah:-OFO_FaD1NRmq72QCHSM:bpzshe1) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/d9ed062627e491f52ec49007a38fd9bf6052e9f4/src/components/text-editor.vue#L179)):*
<details><summary><i>Previously, RyanCoulsonCA (Ryan Coulson) wrote…</i></summary><blockquote>

This one still seems to be happening for me after the changes:
![scrollbartext.gif](https://files.reviewableusercontent.io/images/reviewable/25874602/1lAAXd6z61119WbaOpab-pFI/scrollbartext.gif)
</blockquote></details>

Donethanks, I also fixed the issue for the other three toggles on the right side of the editor. 


<!-- Sent from Reviewable.io -->

2024-12-31 15:44 UTC, RyanCoulsonCA approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2024-12-31 16:00 UTC, yileifeng requested changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: all files reviewed, 1 unresolved discussion (waiting on @IshavSohal)

___
*[`src/components/text-editor.vue` line 161 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485#-OFSQWIB1r3DGIRwZdWA:-OFSQWIB1r3DGIRwZdWB:b2rymtn) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b99aed6f07d3cec392901e77157a6e54df37eef5/src/components/text-editor.vue#L161)):*
> ```Vue
>     };
> 
>     toolbarTooltipAdjust(toggle): void {
> ```

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/Xo4-pJlYylG-GS-VBOT53CuE/image.png)

Changes caused fullscreen toggle tooltip in the text editor to drag out which becomes unreadable  


<!-- Sent from Reviewable.io -->

2024-12-31 22:29 UTC, IshavSohal reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA and @yileifeng)

___
*[`src/components/text-editor.vue` line 161 at r2](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485#-OFSQWIB1r3DGIRwZdWA:-OFToTz_1hH9sQqq0rWc:b-ptuvlw) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b99aed6f07d3cec392901e77157a6e54df37eef5/src/components/text-editor.vue#L161)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/31557789/Xo4-pJlYylG-GS-VBOT53CuE/image.png)

Changes caused fullscreen toggle tooltip in the text editor to drag out which becomes unreadable
</blockquote></details>

Donethanks, I decided to add some right padding to the right side of the toolbar to fix this


<!-- Sent from Reviewable.io -->

2025-01-02 16:16 UTC, yileifeng approved these changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-07 20:31 UTC, gordlin approved these changes
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-10 22:03 UTC, IshavSohal reviewed
Donethanks

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485#-:-OGHEg73Er3NKYOJN6cR:bah2568)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @gordlin, @szczz, and @yileifeng)



<!-- Sent from Reviewable.io -->

2025-01-20 16:16 UTC, szczz approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/485)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @IshavSohal)



<!-- Sent from Reviewable.io -->

2025-01-20 16:16 UTC, merged