add export product button
ramp4-pcar4/storylines-editor pull request #493
Opened 2024-12-19 19:58 UTC by RyanCoulsonCA

### Related Item(s)
#310 

### Changes
- Added a new button that allows you to export the product as a ZIP.

### Notes
I've added this button to the top right corner with the help button for now, but I'm open to feedback on where we should place this.

### Testing
Steps:
1. Open the demo link.
2. Load a product.
3. Click the button and ensure that the product downloads successfully. If the download fails for whatever reason, an error message should appear instead.

2024-12-20 14:55 UTC, mohsin-r requested changes
Cool feature! There's a tad bit of inconsistent behaviour I found. If you add a new slide to a product, and its a slide that has some sort of assets like map, image, etc., then if you export the product (without clicking on save changes) the new unsaved slide won't be there in the main config but the assets will be there in the assets folder, which feels inconsistent. Perhaps we can "save" (update the `configFileStructure` but not actually call the `upload` endpoint) on export and then provide the zipped folder? Or do we not want any unsaved changes to go into the exported zip?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493#-:-OEZY8Q47xYclOV9sIyW:b-fyb5cj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-20 19:28 UTC, RyanCoulsonCA reviewed
Great catch, apparently I forgot how we save the config files. I've added a new flag to the `generateConfig` function to save everything without uploading to the server, and I've also made sure that `saveChanges()` is called for the currently-active panel editor as well.

> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493#-:-OEZtZ3mDWeqqwhls4on:b1ybrw0)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @mohsin-r)



<!-- Sent from Reviewable.io -->

2024-12-20 19:58 UTC, mohsin-r approved these changes
Nice!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493#-:-OE_dWl7Az9DuHYjt94N:b-83sjoh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-24 16:54 UTC, gordlin approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-30 19:01 UTC, szczz approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2024-12-31 16:36 UTC, yileifeng approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-02 20:12 UTC, IshavSohal approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-03 15:28 UTC, spencerwahl approved these changes
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/493)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2025-01-10 15:50 UTC, merged