normalize file saving between slides; add server files
ramp4-pcar4/storylines-editor pull request #64
Opened 2023-02-07 16:33 UTC by RyanCoulsonCA

Closes #54, #51, and #63

# Changes in this PR
* #54: The editor now relies on the Express server for downloading and saving data.
* Added the Express server code to the repo 
* As discussed in #60: Normalized how our current slide editors save data. All media and configuration files are now saved in the ZIP file, and can be easily accessed if needed.
* #51: If a UID is requested and does not exist on the server, an error is displayed.
* #63: Swapping between left and right panels will save contents before switching.

# Set-up
Since the editor now requires the server to be running to work, I've included the code in the repo. 

To set up this server, go into the `server` directory and run `npm i`, then run `node index.js`. This should launch the server locally at `localhost:6040`.

You can then serve the Storylines editor locally as usual, with `npm run serve`. Just use a different terminal window so you can have both running at once.

The editor will access products from (and will save them to) the `server/public/` directory. The `TARGET_PATH` variable in the server code can be modified to change the target directory to the main `public/` folder, but this causes the whole app to reload due to the automatic refresh on code change which is why I didn't do this myself.

If there's any confusion with the ZIP file or the server stuff, feel free to ask me!

2023-02-07 19:51 UTC, yileifeng requested changes
Nice work ✅

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-:-NNhC3kf0ZjN0_508m3d:b2kyf84)* status: all files reviewed, 2 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`server/package.json` line 14 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-NNhCA6a7iSnRrde98uI:-NNhCA6a7iSnRrde98uJ:buzc58k) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b8ee9824bb53ab950eb0755238f77a161814ed0a/server/package.json#L14)):*
> ```JSON
>         "archiver": "^5.3.1",
>         "body-parser": "^1.20.1",
>         "connect-busboy": "^1.0.0",
> ```

unused?
___
*[`src/components/editor/chart-editor.vue` line 121 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-NNhQIdd0_RrkrBckgi-:-NNhQIdd0_RrkrBckgi0:b-d36a9v) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b8ee9824bb53ab950eb0755238f77a161814ed0a/src/components/editor/chart-editor.vue#L121)):*
> ```Vue
>                 name: chart.title.text,
>                 src: `${this.configFileStructure.uuid}/charts/en/${chart.title.text}.json`,
>                 config: chart
> ```

think this should be safe to be removed as discussed


<!-- Sent from Reviewable.io -->

2023-02-07 19:57 UTC, yileifeng reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64)* status: all files reviewed, 3 unresolved discussions (waiting on @RyanCoulsonCA)

___
*[`src/components/panels/helpers/chart.vue` line 67 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-NNhRbTzDJLVjXWuDMAw:-NNhRbTzDJLVjXWuDMAx:brqgwjg) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b8ee9824bb53ab950eb0755238f77a161814ed0a/src/components/panels/helpers/chart.vue#L67)):*
> ```Vue
> 
>             if (extension === 'json') {
>                 if (this.configFileStructure.config.file(assetSrc)) {
> ```

just a note for preview feature #7 to review this code for `image.vue` to read from ZIP for image files


<!-- Sent from Reviewable.io -->

2023-02-08 13:29 UTC, RyanCoulsonCA reviewed
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @yileifeng)

___
*[`server/package.json` line 14 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-NNhCA6a7iSnRrde98uI:-NNlAqCl4yRkV4yZ2b94:b-896fix) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b8ee9824bb53ab950eb0755238f77a161814ed0a/server/package.json#L14)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

unused?
</blockquote></details>

Done.
___
*[`src/components/editor/chart-editor.vue` line 121 at r1](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64#-NNhQIdd0_RrkrBckgi-:-NNlC6yP5B0_oVpSSXY8:b-896fix) ([raw file](https://github.com/ramp4-pcar4/storylines-editor/blob/b8ee9824bb53ab950eb0755238f77a161814ed0a/src/components/editor/chart-editor.vue#L121)):*
<details><summary><i>Previously, yileifeng (Yi Lei Feng) wrote…</i></summary><blockquote>

think this should be safe to be removed as discussed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-08 14:08 UTC, spencerwahl approved these changes
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64)* status: all files reviewed, 3 unresolved discussions (waiting on @yileifeng)



<!-- Sent from Reviewable.io -->

2023-02-08 14:28 UTC, yileifeng approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64)* status: all files reviewed, 1 unresolved discussion (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-02-08 16:26 UTC, yileifeng approved these changes
> *[Reviewable](https://reviewable.io/reviews/ramp4-pcar4/storylines-editor/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RyanCoulsonCA)



<!-- Sent from Reviewable.io -->

2023-02-08 16:28 UTC, merged